/* ═══════════════════════════════════════════════════════
   MAISON CONSCIENTE — Maellis Constants
   RSS sources, local recipes, fun facts, jokes, quotes, greetings.
   ═══════════════════════════════════════════════════════ */

// ─── RSS Sources ─────────────────────────────────────────

export interface RSSSource {
  id: string;
  name: string;
  url: string;
  category: 'general' | 'sport' | 'culture' | 'tech' | 'horoscope';
  active: boolean;
}

export const RSS_SOURCES: RSSSource[] = [
  { id: 'franceinfo', name: 'France Info', url: 'https://www.francetvinfo.fr/titres.rss', category: 'general', active: true },
  { id: 'lemonde', name: 'Le Monde', url: 'https://www.lemonde.fr/rss/une.xml', category: 'general', active: true },
  { id: 'lequipe', name: "L'Équipe", url: 'https://dwh.lequipe.fr/api/edito/rss?path=/', category: 'sport', active: true },
  { id: 'leparisien', name: 'Le Parisien', url: 'https://www.leparisien.fr/rss/une.xml', category: 'general', active: true },
  { id: 'horoscope', name: 'Horoscope', url: 'https://www.mon-horoscope-du-jour.com/rss.php', category: 'horoscope', active: true },
];

// ─── Local Recipes ──────────────────────────────────────

export interface LocalRecipe {
  id: string;
  title: string;
  description: string;
  prepTimeMin: number;
  cookTimeMin: number;
  servings: number;
  difficulty: 'facile' | 'moyen' | 'difficile';
  tags: string[];
  ingredients: string[];
  steps: string[];
}

export const LOCAL_RECIPES: LocalRecipe[] = [
  // ═══════════════════════════════════════════
  // ENTRÉES (10)
  // ═══════════════════════════════════════════

  {
    id: 'entree-01',
    title: 'Soupe à l\'oignon gratinée',
    description: 'Un classique réconfortant de la cuisine française au fromage fondant.',
    prepTimeMin: 20,
    cookTimeMin: 40,
    servings: 4,
    difficulty: 'moyen',
    tags: ['soupe', 'gratin', 'classique', 'hiver'],
    ingredients: [
      '6 gros oignons jaunes',
      '50 g de beurre',
      '1 cuillère à soupe de sucre',
      '1 litre de bouillon de bœuf',
      '200 ml de vin blanc sec',
      '4 tranches de pain de campagne',
      '200 g de gruyère râpé',
      'Sel et poivre',
    ],
    steps: [
      'Émincez finement les oignons.',
      'Faites fondre le beurre dans une grande cocotte.',
      'Ajoutez les oignons et faites revenir 20 minutes à feu doux.',
      'Saupoudrez de sucre et laissez caraméliser 5 minutes.',
      'Versez le vin blanc et laissez réduire de moitié.',
      'Ajoutez le bouillon, salez et poivrez.',
      'Laissez mijoter 15 minutes à feu doux.',
      'Servez dans des bols avec une tranche de pain et du gruyère râpé.',
      'Passez au four à 200 degrés 10 minutes jusqu\'à ce que le fromage soit doré.',
    ],
  },
  {
    id: 'entree-02',
    title: 'Salade niçoise',
    description: 'Une salade méditerranéenne fraîche et colorée de Nice.',
    prepTimeMin: 20,
    cookTimeMin: 0,
    servings: 4,
    difficulty: 'facile',
    tags: ['salade', 'froid', 'été', 'méditerranéen'],
    ingredients: [
      '400 g de thon en boîte',
      '4 œufs durs',
      '200 g de haricots verts cuits',
      '4 tomates moyennes',
      '1 concombre',
      '100 g d\'olives noires',
      '2 poivrons rouges',
      '2 cuillères à soupe de câpres',
      '4 anchois',
      'Huile d\'olive, vinaigre, sel, poivre',
    ],
    steps: [
      'Coupez les tomates en quartiers et le concombre en rondelles.',
      'Tranchez les poivrons rouges en lanières.',
      'Écalez les œufs durs et coupez-les en deux.',
      'Égouttez le thon et émiettez-le grossièrement.',
      'Disposez la salade sur un grand plat.',
      'Répartissez harmonieusement tous les ingrédients.',
      'Parsemez de câpres et d\'olives noires.',
      'Assaisonnez avec l\'huile d\'olive et le vinaigre.',
      'Servez frais avec du pain de campagne.',
    ],
  },
  {
    id: 'entree-03',
    title: 'Quiche lorraine',
    description: 'La quiche emblématique de la Lorraine au lard fumé.',
    prepTimeMin: 20,
    cookTimeMin: 35,
    servings: 6,
    difficulty: 'moyen',
    tags: ['quiche', 'lardon', 'classique', 'fromage'],
    ingredients: [
      '1 pâte brisée',
      '200 g de lardons fumés',
      '3 œufs',
      '200 ml de crème fraîche',
      '200 ml de lait',
      '100 g de gruyère râpé',
      'Sel, poivre, muscade',
    ],
    steps: [
      'Préchauffez le four à 180 degrés.',
      'Étalez la pâte brisée dans un moule à tarte.',
      'Faites revenir les lardons à la poêle sans matière grasse.',
      'Battez les œufs avec la crème et le lait.',
      'Ajoutez le sel, le poivre et une pincée de muscade.',
      'Répartissez les lardons sur la pâte.',
      'Versez le mélange aux œufs par-dessus.',
      'Parsemez de gruyère râpé.',
      'Enfournez 35 minutes jusqu\'à ce que la quiche soit dorée.',
    ],
  },
  {
    id: 'entree-04',
    title: 'Vichyssoise',
    description: 'Une soupe froide crémeuse à base de poireaux et pommes de terre.',
    prepTimeMin: 15,
    cookTimeMin: 30,
    servings: 4,
    difficulty: 'facile',
    tags: ['soupe', 'froid', 'crème', 'été'],
    ingredients: [
      '4 poireaux',
      '3 pommes de terre',
      '1 oignon',
      '50 g de beurre',
      '500 ml de bouillon de volaille',
      '200 ml de crème fraîche',
      'Sel, poivre, cerfeuil',
    ],
    steps: [
      'Coupez les poireaux en rondelles et les pommes de terre en cubes.',
      'Faites fondre le beurre dans une cocotte.',
      'Faites revenir l\'oignon émincé puis ajoutez les poireaux.',
      'Ajoutez les pommes de terre et le bouillon.',
      'Laissez cuire 30 minutes à feu doux.',
      'Mixez la soupe jusqu\'à obtenir une texture lisse.',
      'Incorporez la crème fraîche.',
      'Salez, poivrez et réfrigérez au moins 2 heures.',
      'Servez bien froide avec des feuilles de cerfeuil.',
    ],
  },
  {
    id: 'entree-05',
    title: 'Pâté en croûte',
    description: 'Un pâté traditionnel cuit dans une pâte feuilletée dorée.',
    prepTimeMin: 40,
    cookTimeMin: 50,
    servings: 8,
    difficulty: 'difficile',
    tags: ['pâté', 'viande', 'feuilleté', 'fête'],
    ingredients: [
      '500 g de pâte feuilletée',
      '300 g de porc haché',
      '200 g de veau haché',
      '100 g de foie de volaille',
      '2 œufs',
      '50 g de pistaches',
      '1 cuillère à café de quatre-épices',
      'Sel, poivre',
      '1 jaune d\'œuf pour dorer',
    ],
    steps: [
      'Préchauffez le four à 180 degrés.',
      'Mélangez les viandes hachées avec les œufs entiers.',
      'Ajoutez le four, le poivre et les quatre-épices.',
      'Incorporez les pistaches concassées.',
      'Garnissez un moule à cake avec la moitié de la pâte.',
      'Versez la farce et tassez bien.',
      'Couvrez avec le reste de pâte et soudez les bords.',
      'Dorez avec le jaune d\'œuf et faites des cheminées.',
      'Enfournez 50 minutes. Laissez refroidir avant de couper.',
    ],
  },
  {
    id: 'entree-06',
    title: 'Œufs mayonnaise',
    description: 'Un classique des apéritifs français, simple et toujours apprécié.',
    prepTimeMin: 15,
    cookTimeMin: 10,
    servings: 4,
    difficulty: 'facile',
    tags: ['œuf', 'mayonnaise', 'apéritif', 'classique'],
    ingredients: [
      '6 œufs',
      '3 cuillères à soupe de mayonnaise',
      '1 cuillère à café de moutarde de Dijon',
      'Paprika',
      'Ciboulette fraîche',
      'Sel, poivre',
    ],
    steps: [
      'Faites cuire les œufs durs pendant 10 minutes dans l\'eau bouillante.',
      'Passez-les sous l\'eau froide et écalez-les.',
      'Coupez chaque œuf en deux dans le sens de la longueur.',
      'Retirez les jaunes et écrasez-les dans un bol.',
      'Mélangez les jaunes avec la mayonnaise et la moutarde.',
      'Salez et poivrez le mélange.',
      'Garnissez les blancs d\'œuf avec cette préparation.',
      'Saupoudrez de paprika et de ciboulette ciselée.',
      'Réfrigérez 30 minutes avant de servir.',
    ],
  },
  {
    id: 'entree-07',
    title: 'Soupe de potimarron',
    description: 'Une velouté onctueux de potimarron au goût de châtaigne.',
    prepTimeMin: 10,
    cookTimeMin: 25,
    servings: 4,
    difficulty: 'facile',
    tags: ['soupe', 'velouté', 'automne', 'végétarien'],
    ingredients: [
      '1 potimarron de 800 g',
      '1 oignon',
      '2 gousses d\'ail',
      '500 ml de bouillon de légumes',
      '100 ml de crème fraîche',
      'Huile d\'olive, sel, poivre',
      'Graines de courge pour décorer',
    ],
    steps: [
      'Coupez le potimarron en morceaux après l\'avoir épépiné.',
      'Émincez l\'oignon et hachez l\'ail.',
      'Faites revenir l\'oignon et l\'ail dans l\'huile d\'olive.',
      'Ajoutez les morceaux de potimarron.',
      'Versez le bouillon et portez à ébullition.',
      'Laissez cuire 25 minutes à couvert.',
      'Mixez finement la soupe.',
      'Incorporez la crème fraîche hors du feu.',
      'Servez parsemé de graines de courge toastées.',
    ],
  },
  {
    id: 'entree-08',
    title: 'Tartare de saumon',
    description: 'Un tartare frais de saumon aux saveurs d\'agrumes et d\'aneth.',
    prepTimeMin: 20,
    cookTimeMin: 0,
    servings: 4,
    difficulty: 'moyen',
    tags: ['saumon', 'froid', 'frais', 'prestige'],
    ingredients: [
      '400 g de saumon frais sans arêtes',
      '1 échalote',
      '1 citron vert',
      '2 cuillères à soupe de câpres',
      '2 cuillères à soupe d\'aneth frais',
      '1 cuillère à soupe d\'huile d\'olive',
      'Sauce soja',
      'Sel, poivre',
    ],
    steps: [
      'Coupez le saumon en petits dés de 5 millimètres.',
      'Hachez finement l\'échalote et les câpres.',
      'Ciseliez l\'aneth frais.',
      'Mélangez le saumon avec l\'échalote et les câpres.',
      'Ajoutez le jus de citron vert et l\'huile d\'olive.',
      'Assaisonnez avec la sauce soja, le sel et le poivre.',
      'Incorporez l\'aneth ciselé délicatement.',
      'Réfrigérez 30 minutes avant de servir.',
      'Dressez avec un emporte-pièce et décorez d\'aneth.',
    ],
  },
  {
    id: 'entree-09',
    title: 'Gratin dauphinois',
    description: 'Un gratin de pommes de terre à la crème, fondant et réconfortant.',
    prepTimeMin: 15,
    cookTimeMin: 60,
    servings: 6,
    difficulty: 'facile',
    tags: ['gratin', 'pommes de terre', 'crème', 'hiver'],
    ingredients: [
      '1 kg de pommes de terre à chair ferme',
      '400 ml de crème liquide',
      '300 ml de lait',
      '2 gousses d\'ail',
      '50 g de beurre',
      'Muscade en poudre',
      'Sel, poivre',
    ],
    steps: [
      'Préchauffez le four à 160 degrés.',
      'Épluchez les pommes de terre et coupez-les en fines rondelles.',
      'Frottez un plat à gratin avec la gousse d\'ail coupée.',
      'Faites chauffer la crème et le lait avec l\'ail restant haché.',
      'Assaisonnez avec le sel, le poivre et la muscade.',
      'Disposez les rondelles de pommes de terre en couches.',
      'Versez le mélange crémeux sur les pommes de terre.',
      'Ajoutez des noisettes de beurre sur le dessus.',
      'Enfournez 60 minutes jusqu\'à ce que le dessus soit doré.',
    ],
  },
  {
    id: 'entree-10',
    title: 'Fondue de poireaux',
    description: 'Des poireaux fondus à la crème, un accompagnement élégant.',
    prepTimeMin: 10,
    cookTimeMin: 25,
    servings: 4,
    difficulty: 'facile',
    tags: ['poireau', 'crème', 'végétarien', 'hiver'],
    ingredients: [
      '6 poireaux',
      '50 g de beurre',
      '200 ml de crème fraîche',
      '1 cuillère à soupe de farine',
      'Muscade',
      'Sel, poivre',
    ],
    steps: [
      'Coupez les poireaux en tronçons et lavez-les soigneusement.',
      'Faites fondre le beurre dans une cocotte.',
      'Ajoutez les poireaux égouttés.',
      'Couvez et laissez cuire 20 minutes à feu doux.',
      'Saupoudrez de farine et mélangez bien.',
      'Versez la crème fraîche en remuant.',
      'Assaisonnez avec le sel, le poivre et la muscade.',
      'Laissez épaissir 5 minutes sans cesser de remuer.',
      'Servez chaud accompagné de viande ou de poisson.',
    ],
  },

  // ═══════════════════════════════════════════
  // PLATS PRINCIPAUX (15)
  // ═══════════════════════════════════════════

  {
    id: 'plat-01',
    title: 'Coq au vin',
    description: 'Le grand classique français de poulet mijoté au vin rouge.',
    prepTimeMin: 30,
    cookTimeMin: 120,
    servings: 6,
    difficulty: 'moyen',
    tags: ['poulet', 'vin rouge', 'mijoté', 'classique'],
    ingredients: [
      '1 coq entier découpé ou 8 cuisses de poulet',
      '1 bouteille de vin rouge',
      '200 g de lardons',
      '200 g de champignons de Paris',
      '2 carottes',
      '1 oignon',
      '2 gousses d\'ail',
      '50 g de farine',
      'Bouquet garni',
      '25 g de beurre',
      'Sel, poivre',
    ],
    steps: [
      'Faites mariner le poulet dans le vin rouge avec le bouquet garni toute une nuit.',
      'Égouttez le poulet et séchez-le bien.',
      'Faites dorer le poulet dans le beurre chaud.',
      'Retirez le poulet et faites revenir les lardons.',
      'Ajoutez les carottes et l\'oignon émincé.',
      'Saupoudrez de farine et mélangez.',
      'Remettez le poulet et versez le vin de marinade.',
      'Ajoutez les champignons et l\'ail.',
      'Couvez et laissez mijoter 2 heures à feu doux.',
      'Servez chaud avec des pommes de terre vapeur ou du riz.',
    ],
  },
  {
    id: 'plat-02',
    title: 'Bœuf bourguignon',
    description: 'Un ragoût de bœuf au vin rouge de Bourgogne, un incontournable.',
    prepTimeMin: 30,
    cookTimeMin: 180,
    servings: 6,
    difficulty: 'moyen',
    tags: ['bœuf', 'vin rouge', 'mijoté', 'classique'],
    ingredients: [
      '1 kg de bœuf (paleron ou gîte) coupé en cubes',
      '1 bouteille de vin rouge de Bourgogne',
      '200 g de lardons',
      '250 g de champignons de Paris',
      '200 g de petits oignons grelots',
      '3 carottes',
      '2 cuillères à soupe de farine',
      '2 gousses d\'ail',
      'Bouquet garni',
      'Huile, sel, poivre',
    ],
    steps: [
      'Coupez le bœuf en gros cubes de 4 centimètres.',
      'Faites dorer les cubes de bœuf dans l\'huile chaude.',
      'Retirez la viande et faites revenir les lardons.',
      'Ajoutez les carottes en rondelles et les oignons.',
      'Saupoudrez de farine et mélangez bien.',
      'Versez le vin rouge et ajoutez le bouquet garni.',
      'Remettez le bœuf dans la cocotte.',
      'Couvez et laissez mijoter 3 heures à feu très doux.',
      'Ajoutez les champignons 30 minutes avant la fin.',
      'Servez avec des pommes de terre ou des pâtes fraîches.',
    ],
  },
  {
    id: 'plat-03',
    title: 'Ratatouille',
    description: 'Un plat provençal de légumes du soleil mijotés à l\'huile d\'olive.',
    prepTimeMin: 25,
    cookTimeMin: 45,
    servings: 6,
    difficulty: 'facile',
    tags: ['légumes', 'méditerranéen', 'été', 'végétarien'],
    ingredients: [
      '2 aubergines',
      '2 courgettes',
      '4 tomates mûres',
      '2 poivrons (rouge et vert)',
      '1 oignon',
      '4 gousses d\'ail',
      'Huile d\'olive',
      'Herbes de Provence',
      'Basilic frais',
      'Sel, poivre',
    ],
    steps: [
      'Coupez tous les légumes en gros cubes.',
      'Faites revenir l\'oignon émincé dans l\'huile d\'olive.',
      'Ajoutez les poivrons et laissez cuire 5 minutes.',
      'Incorporez les aubergines et les courgettes.',
      'Ajoutez les tomates coupées en morceaux.',
      'Hachez l\'ail et ajoutez-le aux légumes.',
      'Assaisonnez avec les herbes de Provence, le sel et le poivre.',
      'Couvez et laissez mijoter 45 minutes à feu doux.',
      'Parsemez de basilic frais avant de servir.',
    ],
  },
  {
    id: 'plat-04',
    title: 'Blanquette de veau',
    description: 'Un ragoût crémeux de veau aux carottes et champignons.',
    prepTimeMin: 20,
    cookTimeMin: 90,
    servings: 6,
    difficulty: 'moyen',
    tags: ['veau', 'crème', 'mijoté', 'classique'],
    ingredients: [
      '1 kg d\'épaule de veau coupée en cubes',
      '3 carottes',
      '200 g de champignons de Paris',
      '2 oignons',
      '1 bouquet garni',
      '50 g de beurre',
      '2 jaunes d\'œufs',
      '200 ml de crème fraîche',
      'Jus de citron',
      'Sel, poivre',
    ],
    steps: [
      'Blanchissez le veau 5 minutes dans l\'eau bouillante et égouttez.',
      'Faites fondre le beurre et y faire blondir les oignons.',
      'Ajoutez le veau et les carottes en rondelles.',
      'Recouvrez d\'eau et ajoutez le bouquet garni.',
      'Laissez mijoter 1 heure et demie à couvert.',
      'Ajoutez les champignons 20 minutes avant la fin.',
      'Retirez la viande et filtrez le bouillon.',
      'Mélangez les jaunes d\'œufs avec la crème et le jus de citron.',
      'Versez ce mélange sur le bouillon chaud sans bouillir.',
      'Remettez la viande et servez avec du riz.',
    ],
  },
  {
    id: 'plat-05',
    title: 'Cassoulet',
    description: 'Le cassoulet traditionnel au haricots blancs, confit et saucisses.',
    prepTimeMin: 30,
    cookTimeMin: 180,
    servings: 8,
    difficulty: 'difficile',
    tags: ['haricots', 'confit', 'saucisse', 'sud-ouest'],
    ingredients: [
      '500 g de haricots blancs secs',
      '4 cuisses de confit de canard',
      '4 saucisses de Toulouse',
      '200 g de lardons',
      '2 oignons',
      '4 gousses d\'ail',
      '2 carottes',
      '1 boîte de tomates concassées',
      'Bouquet garni',
      'Chapelure',
    ],
    steps: [
      'Faites tremper les haricots blancs toute une nuit.',
      'Égouttez les haricots et faites-les cuire 45 minutes.',
      'Faites dorer les lardons et les oignons émincés.',
      'Ajoutez les carottes et les tomates concassées.',
      'Incorporez les haricots et le bouquet garni.',
      'Déposez les saucisses et le confit de canard dessus.',
      'Ajoutez de l\'eau à hauteur et portez à ébullition.',
      'Couvrez et enfournez à 150 degrés pour 3 heures.',
      'Parsemez de chapelure et repassez au four 30 minutes.',
    ],
  },
  {
    id: 'plat-06',
    title: 'Gratin de chou-fleur au gratin',
    description: 'Un gratin crémeux de chou-fleur au fromage, un classique familial.',
    prepTimeMin: 15,
    cookTimeMin: 35,
    servings: 4,
    difficulty: 'facile',
    tags: ['chou-fleur', 'gratin', 'fromage', 'végétarien'],
    ingredients: [
      '1 gros chou-fleur',
      '50 g de beurre',
      '50 g de farine',
      '500 ml de lait',
      '200 g de gruyère râpé',
      'Muscade',
      'Sel, poivre',
    ],
    steps: [
      'Préchauffez le four à 200 degrés.',
      'Coupez le chou-fleur en bouquets.',
      'Faites cuire les bouquets 10 minutes à la vapeur.',
      'Faites fondre le beurre et ajoutez la farine.',
      'Versez le lait progressivement en fouettant.',
      'Assaisonnez avec la muscade, le sel et le poivre.',
      'Disposez le chou-fleur dans un plat à gratin.',
      'Versez la béchamel sur le chou-fleur.',
      'Parsemez de gruyère et enfournez 25 minutes.',
    ],
  },
  {
    id: 'plat-07',
    title: 'Magret de canard',
    description: 'Des magrets de canard poêlés, croustillants à l\'extérieur et rosés.',
    prepTimeMin: 10,
    cookTimeMin: 20,
    servings: 4,
    difficulty: 'moyen',
    tags: ['canard', 'poêlé', 'prestige', 'sud-ouest'],
    ingredients: [
      '2 magrets de canard',
      '2 cuillères à soupe de miel',
      '2 cuillères à soupe de vinaigre balsamique',
      '4 pommes golden',
      '25 g de beurre',
      'Sel, poivre',
    ],
    steps: [
      'Entaillez la peau des magrets en losange.',
      'Assaisonnez les magrets de sel et de poivre.',
      'Placez les magrets côté peau dans une poêle froide.',
      'Faites cuire 8 minutes à feu moyen côté peau.',
      'Retournez et cuisez 5 minutes côté chair.',
      'Laissez reposer la viande 5 minutes sous alu.',
      'Dans la même poêle, faites caraméliser les pommes en cubes.',
      'Déglacez avec le miel et le vinaigre balsamique.',
      'Tranchez les magrets et servez avec les pommes caramélisées.',
    ],
  },
  {
    id: 'plat-08',
    title: 'Tarte provençale aux légumes',
    description: 'Une tarte aux légumes du soleil, parfaite en été.',
    prepTimeMin: 20,
    cookTimeMin: 35,
    servings: 6,
    difficulty: 'facile',
    tags: ['tarte', 'légumes', 'méditerranéen', 'été'],
    ingredients: [
      '1 pâte brisée',
      '2 courgettes',
      '2 tomates',
      '1 aubergine',
      '1 poivron rouge',
      '1 oignon rouge',
      '100 g de feta',
      'Herbes de Provence',
      'Huile d\'olive, sel, poivre',
    ],
    steps: [
      'Préchauffez le four à 180 degrés.',
      'Étalez la pâte dans un moule à tarte.',
      'Coupez tous les légumes en fines rondelles.',
      'Disposez les rondelles en alternant les couleurs.',
      'Émincez l\'oignon rouge et répartissez-le dessus.',
      'Arrosez d\'huile d\'olive et saupoudrez d\'herbes.',
      'Émiettez la feta sur le dessus.',
      'Assaisonnez avec le sel et le poivre.',
      'Enfournez 35 minutes jusqu\'à ce que les légumes soient fondants.',
    ],
  },
  {
    id: 'plat-09',
    title: 'Bouillabaisse',
    description: 'La soupe de poisson emblématique de Marseille.',
    prepTimeMin: 40,
    cookTimeMin: 40,
    servings: 6,
    difficulty: 'difficile',
    tags: ['poisson', 'soupe', 'Provence', 'prestige'],
    ingredients: [
      '1 kg de poissons de roche',
      '400 g de rascasse ou lotte',
      '8 moules',
      '4 tomates',
      '2 oignons',
      '3 gousses d\'ail',
      '1 fenouil',
      'Safran',
      'Huile d\'olive, pastis',
      'Sel, poivre',
    ],
    steps: [
      'Nettoyez soigneusement tous les poissons et fruits de mer.',
      'Faites revenir les oignons, l\'ail et le fenouil dans l\'huile.',
      'Ajoutez les tomates concassées et le pastis.',
      'Versez 2 litres d\'eau et ajoutez le safran.',
      'Ajoutez les poissons de roche et laissez mijoter 20 minutes.',
      'Retirez les gros morceaux de poisson.',
      'Mixez le bouillon avec les légumes pour obtenir une soupe épaisse.',
      'Faites cuire la rascasse et les moules dans le bouillon.',
      'Servez la soupe avec des croûtons et de la rouille.',
    ],
  },
  {
    id: 'plat-10',
    title: 'Confit de canard',
    description: 'Des cuisses de canard confites lentement dans leur graisse.',
    prepTimeMin: 15,
    cookTimeMin: 180,
    servings: 4,
    difficulty: 'moyen',
    tags: ['canard', 'confit', 'sud-ouest', 'classique'],
    ingredients: [
      '4 cuisses de canard',
      '500 g de graisse de canard',
      '4 gousses d\'ail',
      '2 cuillères à café de sel',
      '1 cuillère à café de poivre en grains',
      'Thym, laurier',
      'Pommes de terre grenaille',
    ],
    steps: [
      'Frottez les cuisses de canard avec le sel.',
      'Laissez reposer 12 heures au réfrigérateur.',
      'Rincez et séchez les cuisses.',
      'Faites fondre la graisse de canard dans une cocotte.',
      'Plongez les cuisses dans la graisse fondue.',
      'Ajoutez l\'ail, le thym et le laurier.',
      'Couvrez et enfournez à 130 degrés pour 3 heures.',
      'Les cuisses doivent être tendres et dorées.',
      'Servez avec des pommes de terre grenaille rôties.',
    ],
  },
  {
    id: 'plat-11',
    title: 'Poulet basquaise',
    description: 'Un poulet mijoté aux poivrons et jambon de Bayonne.',
    prepTimeMin: 20,
    cookTimeMin: 60,
    servings: 6,
    difficulty: 'moyen',
    tags: ['poulet', 'poivron', 'Pays basque', 'jambon'],
    ingredients: [
      '1 poulet découpé en 8 morceaux',
      '3 poivrons (rouge, vert, jaune)',
      '2 tomates',
      '100 g de jambon de Bayonne',
      '2 oignons',
      '3 gousses d\'ail',
      'Piment d\'Espelette',
      'Huile d\'olive, sel, poivre',
    ],
    steps: [
      'Faites dorer les morceaux de poulet dans l\'huile d\'olive.',
      'Retirez le poulet et réservez-le.',
      'Faites revenir les oignons et l\'ail émincé.',
      'Ajoutez les poivrons coupés en lanières.',
      'Incorporez les tomates concassées et le jambon en dés.',
      'Saupoudrez de piment d\'Espelette.',
      'Remettez le poulet dans la cocotte.',
      'Couvez et laissez mijoter 45 minutes à feu doux.',
      'Servez chaud avec du riz basmati.',
    ],
  },
  {
    id: 'plat-12',
    title: 'Quenelles de brochet sauce Nantua',
    description: 'Des quenelles légères au brochet, nappées d\'une sauce aux écrevisses.',
    prepTimeMin: 30,
    cookTimeMin: 30,
    servings: 4,
    difficulty: 'difficile',
    tags: ['poisson', 'quenelles', 'sauce', 'Lyon'],
    ingredients: [
      '300 g de chair de brochet',
      '3 œufs',
      '100 g de beurre',
      '100 ml de crème fraîche',
      '50 g de farine',
      '200 ml de lait',
      '200 g de queues d\'écrevisses',
      'Cognac',
      'Sel, poivre, muscade',
    ],
    steps: [
      'Mixez la chair de brochet très finement.',
      'Ajoutez les œufs un par un en mélangeant.',
      'Incorporez la crème et le beurre fondu.',
      'Assaisonnez avec le sel, le poivre et la muscade.',
      'Façonnez les quenelles à la cuillère.',
      'Faites-les pocher 15 minutes dans le bouillon frémissant.',
      'Préparez la béchamel avec la farine et le lait.',
      'Ajoutez les queues d\'écrevisses et un filet de cognac.',
      'Nappez les quenelles de sauce et gratinez au four.',
    ],
  },
  {
    id: 'plat-13',
    title: 'Carbonnade flamande',
    description: 'Un ragoût de bœuf à la bière belge et au pain d\'épices.',
    prepTimeMin: 20,
    cookTimeMin: 150,
    servings: 6,
    difficulty: 'moyen',
    tags: ['bœuf', 'bière', 'mijoté', 'Nord'],
    ingredients: [
      '1 kg de bœuf (paleron) en cubes',
      '75 cl de bière brune',
      '2 oignons',
      '3 tranches de pain d\'épices',
      '2 cuillères à soupe de moutarde',
      '200 g de lardons',
      '2 cuillères à soupe de vinaigre',
      'Sel, poivre, laurier',
    ],
    steps: [
      'Faites dorer les cubes de bœuf dans une cocotte.',
      'Ajoutez les lardons et les oignons émincés.',
      'Versez la bière brune.',
      'Tartinez le pain d\'épices de moutarde.',
      'Déposez le pain sur la viande.',
      'Ajoutez le vinaigre et le laurier.',
      'Couvez et laissez mijoter 2 heures et demie à feu doux.',
      'Le pain va se dissoudre et épaissir la sauce.',
      'Servez avec des frites ou des pommes de terre.',
    ],
  },
  {
    id: 'plat-14',
    title: 'Curry de légumes au lait de coco',
    description: 'Un curry végétarien parfumé au lait de coco.',
    prepTimeMin: 15,
    cookTimeMin: 30,
    servings: 4,
    difficulty: 'facile',
    tags: ['légumes', 'coco', 'curry', 'végétarien'],
    ingredients: [
      '1 courgette',
      '1 aubergine',
      '1 poivron rouge',
      '1 boîte de 400 ml de lait de coco',
      '2 cuillères à soupe de pâte de curry',
      '200 g de tofu ferme',
      '2 oignons',
      '2 gousses d\'ail',
      'Cilantro frais, sel, poivre',
    ],
    steps: [
      'Coupez tous les légumes en cubes.',
      'Coupez le tofu en dés et faites-le dorer dans une poêle.',
      'Faites revenir les oignons et l\'ail dans une cocotte.',
      'Ajoutez la pâte de curry et remuez une minute.',
      'Versez le lait de coco et portez à ébullition.',
      'Ajoutez les légumes et le tofu doré.',
      'Laissez mijoter 25 minutes à couvert.',
      'Assaisonnez avec le sel et le poivre.',
      'Servez parsemé de cilantro frais avec du riz basmati.',
    ],
  },
  {
    id: 'plat-15',
    title: 'Tarte tatin aux tomates cerises',
    description: 'Une variante salée de la tarte tatin avec des tomates cerises confites.',
    prepTimeMin: 15,
    cookTimeMin: 35,
    servings: 6,
    difficulty: 'facile',
    tags: ['tarte', 'tomate', 'invertie', 'été'],
    ingredients: [
      '1 pâte feuilletée',
      '500 g de tomates cerises',
      '100 g de sucre',
      '50 g de beurre',
      '2 cuillères à soupe de vinaigre balsamique',
      '1 bouquet de roquette',
      'Sel, poivre',
    ],
    steps: [
      'Préchauffez le four à 200 degrés.',
      'Faites fondre le sucre dans une poêle jusqu\'à obtenir un caramel.',
      'Ajoutez le beurre et le vinaigre balsamique.',
      'Disposez les tomates cerises entières dans le caramel.',
      'Couvrez avec la pâte feuilletée en rentrant les bords.',
      'Enfournez 30 minutes jusqu\'à ce que la pâte soit dorée.',
      'Laissez refroidir 5 minutes puis retournez sur un plat.',
      'Garnissez de roquette fraîche.',
      'Servez tiède ou à température ambiante.',
    ],
  },

  // ═══════════════════════════════════════════
  // DESSERTS (10)
  // ═══════════════════════════════════════════

  {
    id: 'dessert-01',
    title: 'Crème brûlée',
    description: 'Un dessert emblématique à la crème vanillée et au caramel craquant.',
    prepTimeMin: 15,
    cookTimeMin: 45,
    servings: 6,
    difficulty: 'moyen',
    tags: ['crème', 'vanille', 'caramel', 'classique'],
    ingredients: [
      '500 ml de crème liquide',
      '6 jaunes d\'œufs',
      '100 g de sucre',
      '1 gousse de vanille',
      'Cassonade pour le dessus',
    ],
    steps: [
      'Préchauffez le four à 150 degrés.',
      'Fendez la gousse de vanille et grattez les graines.',
      'Faites chauffer la crème avec la vanille.',
      'Battez les jaunes avec le sucre sans blanchir.',
      'Versez la crème chaude sur les jaunes en remuant.',
      'Filtrez la préparation et versez dans des ramequins.',
      'Enfournez au bain-marie 40 minutes.',
      'Réfrigérez au moins 4 heures.',
      'Saupoudrez de cassonade et caramélisez au chalumeau avant de servir.',
    ],
  },
  {
    id: 'dessert-02',
    title: 'Mousse au chocolat',
    description: 'Une mousse légère et aérienne au chocolat noir intense.',
    prepTimeMin: 20,
    cookTimeMin: 10,
    servings: 6,
    difficulty: 'moyen',
    tags: ['chocolat', 'mousse', 'classique', 'sans cuisson'],
    ingredients: [
      '200 g de chocolat noir 70 pourcent',
      '6 œufs',
      '30 g de sucre',
      '1 pincée de sel',
    ],
    steps: [
      'Faites fondre le chocolat au bain-marie.',
      'Séparez les blancs des jaunes d\'œufs.',
      'Incorporez les jaunes au chocolat fondu.',
      'Battez les blancs en neige avec une pincée de sel.',
      'Ajoutez le sucre aux blancs et continuez de battre.',
      'Incorporez un tiers des blancs au chocolat.',
      'Puis pliez délicatement le reste des blancs.',
      'Versez dans des coupes et réfrigérez 4 heures.',
      'Servez frais avec quelques copeaux de chocolat.',
    ],
  },
  {
    id: 'dessert-03',
    title: 'Tarte tatin',
    description: 'La célèbre tarte aux pommes caramélisée, servie inversée.',
    prepTimeMin: 20,
    cookTimeMin: 40,
    servings: 8,
    difficulty: 'moyen',
    tags: ['pommes', 'tarte', 'caramel', 'classique'],
    ingredients: [
      '1 pâte feuilletée',
      '1 kg de pommes Golden',
      '150 g de beurre',
      '150 g de sucre',
      '1 cuillère à café de cannelle',
      'Jus d\'un demi-citron',
    ],
    steps: [
      'Préchauffez le four à 200 degrés.',
      'Épluchez les pommes et coupez-les en quartiers.',
      'Faites fondre le sucre dans une poêle jusqu\'à un caramel ambré.',
      'Ajoutez le beurre et le jus de citron.',
      'Disposez les quartiers de pommes dans le caramel.',
      'Saupoudrez de cannelle.',
      'Couvrez avec la pâte feuilletée en rentrant les bords.',
      'Enfournez 35 minutes jusqu\'à dorure.',
      'Retournez sur un plat et servez tiède avec de la crème.',
    ],
  },
  {
    id: 'dessert-04',
    title: 'Île flottante',
    description: 'Des blancs d\'œufs en neige sur un lit de crème anglaise.',
    prepTimeMin: 20,
    cookTimeMin: 20,
    servings: 6,
    difficulty: 'moyen',
    tags: ['blancs en neige', 'crème anglaise', 'classique'],
    ingredients: [
      '6 œufs',
      '500 ml de lait',
      '100 g de sucre',
      '1 gousse de vanille',
      'Caramel liquide',
    ],
    steps: [
      'Faites chauffer le lait avec la vanille fendue.',
      'Battez les jaunes avec la moitié du sucre.',
      'Versez le lait chaud sur les jaunes en fouettant.',
      'Remettez sur le feu et remuez jusqu\'à épaississement.',
      'Battez les blancs en neige ferme avec le reste de sucre.',
      'Formez des îles à la cuillère et pochez-les 3 minutes.',
      'Versez la crème anglaise dans des assiettes creuses.',
      'Déposez une île flottante dans chaque assiette.',
      'Nappez de caramel liquide et servez frais.',
    ],
  },
  {
    id: 'dessert-05',
    title: 'Éclair au chocolat',
    description: 'Des choux allongés fourrés de crème au chocolat et glacés.',
    prepTimeMin: 30,
    cookTimeMin: 25,
    servings: 8,
    difficulty: 'difficile',
    tags: ['chocolat', 'pâte à choux', 'pâtisserie'],
    ingredients: [
      'Pour la pâte: 150 ml d\'eau, 80 g de beurre, 100 g de farine, 3 œufs',
      'Pour la crème: 200 ml de lait, 2 jaunes, 50 g de sucre, 100 g de chocolat',
      'Pour le glaçage: 100 g de chocolat, 50 g de beurre',
    ],
    steps: [
      'Préchauffez le four à 200 degrés.',
      'Portez l\'eau et le beurre à ébullition.',
      'Hors du feu, ajoutez la farine d\'un coup et mélangez.',
      'Incorporez les œufs un par un.',
      'Formez des bâtons sur une plaque avec une douille.',
      'Enfournez 25 minutes sans ouvrir le four.',
      'Faites fondre le chocolat dans le lait chaud.',
      'Battez les jaunes avec le sucre et mélangez au chocolat.',
      'Fourrez les éclairs refroidis avec cette crème.',
      'Glacez le dessus avec le chocolat fondu et le beurre.',
    ],
  },
  {
    id: 'dessert-06',
    title: 'Clafoutis aux cerises',
    description: 'Un flan traditionnel du Limousin aux cerises entières.',
    prepTimeMin: 10,
    cookTimeMin: 40,
    servings: 6,
    difficulty: 'facile',
    tags: ['cerises', 'flan', 'classique', 'Limousin'],
    ingredients: [
      '500 g de cerises',
      '3 œufs',
      '100 g de sucre',
      '100 g de farine',
      '250 ml de lait',
      '1 sachet de sucre vanillé',
      'Beurre pour le moule',
      'Pincée de sel',
    ],
    steps: [
      'Préchauffez le four à 180 degrés.',
      'Beurrez un moule à tarte.',
      'Lavez les cerises et laissez-les entières avec les noyaux.',
      'Battez les œufs avec le sucre et le sucre vanillé.',
      'Ajoutez la farine et le sel, puis le lait.',
      'Mélangez pour obtenir une pâte lisse.',
      'Versez les cerises dans le moule.',
      'Recouvrez avec la pâte.',
      'Enfournez 40 minutes. Démoulez tiède et saupoudrez de sucre.',
    ],
  },
  {
    id: 'dessert-07',
    title: 'Paris-Brest',
    description: 'Un entremets en couronne de pâte à choux à la crème mousseline.',
    prepTimeMin: 40,
    cookTimeMin: 30,
    servings: 8,
    difficulty: 'difficile',
    tags: ['pâte à choux', 'crème', 'noisette', 'classique'],
    ingredients: [
      'Pour la pâte: 250 ml d\'eau, 100 g de beurre, 150 g de farine, 5 œufs',
      'Pour la crème: 250 ml de lait, 4 jaunes, 100 g de sucre, 40 g de Maïzena',
      '100 g de pâte de noisette, 150 g de beurre',
      'Amandes effilées, sucre glace',
    ],
    steps: [
      'Préchauffez le four à 200 degrés.',
      'Préparez la pâte à choux comme pour les éclairs.',
      'Formez deux cercles sur une plaque et parsemez d\'amandes.',
      'Enfournez 25 minutes.',
      'Préparez une crème pâtissière avec le lait, les jaunes et le sucre.',
      'Incorporez la pâte de noisette au beurre mou.',
      'Mélangez cette praline à la crème pâtissière refroidie.',
      'Garnissez le cercle du bas avec la crème mousseline.',
      'Refermez avec le second cercle et saupoudrez de sucre glace.',
    ],
  },
  {
    id: 'dessert-08',
    title: 'Fondant au chocolat',
    description: 'Un gâteau au chocolat coulant au centre, irrésistible.',
    prepTimeMin: 15,
    cookTimeMin: 12,
    servings: 4,
    difficulty: 'facile',
    tags: ['chocolat', 'fondant', 'coulant', 'rapide'],
    ingredients: [
      '200 g de chocolat noir',
      '150 g de beurre',
      '3 œufs',
      '80 g de sucre',
      '50 g de farine',
      'Beurre et farine pour les moules',
    ],
    steps: [
      'Préchauffez le four à 200 degrés.',
      'Faites fondre le chocolat et le beurre au bain-marie.',
      'Battez les œufs avec le sucre.',
      'Ajoutez le chocolat fondu aux œufs.',
      'Incorporez la farine en mélangeant doucement.',
      'Beurrez et farinez 4 ramequins.',
      'Versez la pâte dans les moules.',
      'Enfournez 12 minutes, le centre doit rester coulant.',
      'Démoulez immédiatement et servez tiède.',
    ],
  },
  {
    id: 'dessert-09',
    title: 'Tarte aux citrons meringuée',
    description: 'Une tarte acidulée surmontée d\'une meringue dorée et croustillante.',
    prepTimeMin: 30,
    cookTimeMin: 25,
    servings: 8,
    difficulty: 'moyen',
    tags: ['citron', 'meringue', 'tarte', 'classique'],
    ingredients: [
      '1 pâte sablée',
      '3 citrons non traités',
      '150 g de sucre',
      '4 œufs',
      '50 g de Maïzena',
      '150 ml d\'eau',
    ],
    steps: [
      'Préchauffez le four à 180 degrés.',
      'Faites précuire la pâte sablée 15 minutes à blanc.',
      'Pressez les citrons pour obtenir le jus.',
      'Faites un sirop avec l\'eau et la moitié du sucre.',
      'Ajoutez le jus de citron et la Maïzena délayée.',
      'Laissez épaissir en remuant, puis retirez du feu.',
      'Battez les blancs en neige avec le reste du sucre.',
      'Versez la crème au citron sur le fond de tarte.',
      'Couvrez de meringue et enfournez 10 minutes pour dorer.',
    ],
  },
  {
    id: 'dessert-10',
    title: 'Panna cotta aux fruits rouges',
    description: 'Un dessert italien onctueux accompagné de coulis de fruits rouges.',
    prepTimeMin: 15,
    cookTimeMin: 5,
    servings: 4,
    difficulty: 'facile',
    tags: ['crème', 'fruits rouges', 'italien', 'frais'],
    ingredients: [
      '400 ml de crème liquide',
      '100 ml de lait',
      '50 g de sucre',
      '2 feuilles de gélatine',
      '1 gousse de vanille',
      '300 g de fruits rouges mélangés',
      '2 cuillères à soupe de sucre glace',
    ],
    steps: [
      'Faites tremper la gélatine dans l\'eau froide.',
      'Faites chauffer la crème, le lait et le sucre avec la vanille.',
      'Hors du feu, ajoutez la gélatine essorée.',
      'Mélangez bien et versez dans des verrines.',
      'Réfrigérez au moins 4 heures.',
      'Mixez les fruits rouges avec le sucre glace pour le coulis.',
      'Filtrez le coulis si nécessaire.',
      'Nappez la panna cotta de coulis avant de servir.',
    ],
  },

  // ═══════════════════════════════════════════
  // APÉRITIFS / BUFFETS (8)
  // ═══════════════════════════════════════════

  {
    id: 'aperitif-01',
    title: 'Bruschetta tomate basilic',
    description: 'Des tartines italiennes croustillantes garnies de tomates fraîches.',
    prepTimeMin: 15,
    cookTimeMin: 5,
    servings: 6,
    difficulty: 'facile',
    tags: ['tomate', 'pain', 'italien', 'rapide'],
    ingredients: [
      '1 baguette de pain de campagne',
      '4 tomates mûres',
      '1 botte de basilic',
      '2 gousses d\'ail',
      'Huile d\'olive',
      'Vinaigre balsamique',
      'Sel, poivre',
    ],
    steps: [
      'Coupez la baguette en tranches épaisses.',
      'Faites griller les tranches au four ou au grille-pain.',
      'Frottez les tranches avec la gousse d\'ail coupée.',
      'Coupez les tomates en petits dés.',
      'Ciselez le basilic frais.',
      'Mélangez les tomates avec le basilic, l\'huile et le vinaigre.',
      'Assaisonnez avec le sel et le poivre.',
      'Garnissez les tranches de ce mélange.',
      'Servez immédiatement.',
    ],
  },
  {
    id: 'aperitif-02',
    title: 'Tapenade d\'olives noires',
    description: 'Une crème d\'olives provençale parfaite sur du pain grillé.',
    prepTimeMin: 10,
    cookTimeMin: 0,
    servings: 8,
    difficulty: 'facile',
    tags: ['olives', 'apéritif', 'Provence', 'sans cuisson'],
    ingredients: [
      '200 g d\'olives noires dénoyautées',
      '2 filets d\'anchois',
      '1 cuillère à soupe de câpres',
      '2 cuillères à soupe de concentré de tomates',
      '1 gousse d\'ail',
      '3 cuillères à soupe d\'huile d\'olive',
      'Jus de citron',
    ],
    steps: [
      'Égouttez les olives si elles sont en saumure.',
      'Mettez les olives dans un mixeur.',
      'Ajoutez les anchois et les câpres.',
      'Incorporez l\'ail épluché.',
      'Ajoutez le concentré de tomates.',
      'Mixez en ajoutant l\'huile d\'olive progressivement.',
      'Pressez un peu de jus de citron.',
      'Goûtez et ajustez l\'assaisonnement.',
      'Servez sur des toasts ou des crackers.',
    ],
  },
  {
    id: 'aperitif-03',
    title: 'Gougères au fromage',
    description: 'De petits choux salés au gruyère, parfaits pour l\'apéritif.',
    prepTimeMin: 15,
    cookTimeMin: 20,
    servings: 6,
    difficulty: 'moyen',
    tags: ['fromage', 'pâte à choux', 'apéritif', 'Bourgogne'],
    ingredients: [
      '150 ml d\'eau',
      '80 g de beurre',
      '100 g de farine',
      '3 œufs',
      '150 g de gruyère râpé',
      '1 pincée de sel, de poivre et de muscade',
    ],
    steps: [
      'Préchauffez le four à 200 degrés.',
      'Portez l\'eau et le beurre à ébullition.',
      'Retirez du feu et ajoutez la farine d\'un coup.',
      'Mélangez vivement jusqu\'à ce que la pâte se détache.',
      'Ajoutez les œufs un par un en mélangeant.',
      'Incorporez le gruyère râpé et les épices.',
      'Formez des petits tas sur une plaque avec deux cuillères.',
      'Enfournez 20 minutes jusqu\'à ce qu\'ils soient dorés.',
      'Servez tièdes pour l\'apéritif.',
    ],
  },
  {
    id: 'aperitif-04',
    title: 'Houmous maison',
    description: 'Une purée de pois chiches onctueuse au citron et sésame.',
    prepTimeMin: 10,
    cookTimeMin: 0,
    servings: 8,
    difficulty: 'facile',
    tags: ['pois chiches', 'apéritif', 'libanais', 'sans cuisson'],
    ingredients: [
      '400 g de pois chiches en boîte',
      '3 cuillères à soupe de tahini',
      '2 gousses d\'ail',
      'Jus d\'un citron',
      '3 cuillères à soupe d\'huile d\'olive',
      '1 cuillère à café de cumin',
      'Sel, poivre',
      'Paprika pour décorer',
    ],
    steps: [
      'Égouttez et rincez les pois chiches.',
      'Mettez-les dans le mixeur avec le tahini.',
      'Ajoutez l\'ail épluché et le jus de citron.',
      'Mixez en ajoutant l\'huile d\'olive progressivement.',
      'Assaisonnez avec le cumin, le sel et le poivre.',
      'Mixez jusqu\'à obtenir une texture bien lisse.',
      'Versez dans un bol et faites un puits.',
      'Arrosez d\'huile d\'olive et saupoudrez de paprika.',
      'Servez avec du pain pita ou des bâtonnets de légumes.',
    ],
  },
  {
    id: 'aperitif-05',
    title: 'Saumon fumé et fromage frais',
    description: 'Des toasts de saumon fumé au fromage frais et aneth.',
    prepTimeMin: 10,
    cookTimeMin: 0,
    servings: 6,
    difficulty: 'facile',
    tags: ['saumon', 'fromage frais', 'apéritif', 'froid'],
    ingredients: [
      '200 g de saumon fumé',
      '150 g de fromage frais',
      '1 botte d\'aneth',
      '1 citron',
      '12 tranches de pain de mie',
      'Câpres',
      'Sel, poivre',
    ],
    steps: [
      'Mélangez le fromage frais avec l\'aneth ciselé.',
      'Ajoutez le jus d\'un demi-citron.',
      'Assaisonnez avec le sel et le poivre.',
      'Tartinez généreusement les tranches de pain.',
      'Roulez une tranche de saumon sur chaque toast.',
      'Fixez avec un brin d\'aneth.',
      'Ajoutez quelques câpres sur le dessus.',
      'Arrosez d\'un filet de jus de citron.',
      'Servez frais sur un plateau.',
    ],
  },
  {
    id: 'aperitif-06',
    title: 'Mini quiches lorraines',
    description: 'De petites quiches individuelles parfaites pour un buffet.',
    prepTimeMin: 20,
    cookTimeMin: 25,
    servings: 12,
    difficulty: 'moyen',
    tags: ['quiche', 'mini', 'apéritif', 'buffet'],
    ingredients: [
      '2 pâtes feuilletées',
      '200 g de lardons fumés',
      '4 œufs',
      '200 ml de crème fraîche',
      '100 g de gruyère râpé',
      'Sel, poivre, muscade',
    ],
    steps: [
      'Préchauffez le four à 180 degrés.',
      'Découpez des cercles de pâte avec un emporte-pièce.',
      'Garnissez des moules à mini-muffins avec la pâte.',
      'Faites revenir les lardons à sec.',
      'Battez les œufs avec la crème.',
      'Assaisonnez avec le sel, le poivre et la muscade.',
      'Répartissez les lardons dans les moules.',
      'Versez la préparation aux œufs.',
      'Parsemez de gruyère et enfournez 25 minutes.',
    ],
  },
  {
    id: 'aperitif-07',
    title: 'Ceviche de crevettes',
    description: 'Des crevettes marinées au citron vert, avocat et mangue.',
    prepTimeMin: 20,
    cookTimeMin: 0,
    servings: 4,
    difficulty: 'facile',
    tags: ['crevettes', 'froid', 'tropical', 'frais'],
    ingredients: [
      '400 g de crevettes cuites',
      '1 avocat',
      '1 mangue',
      '2 citrons verts',
      '1 échalote',
      '1 cuillère à soupe d\'huile d\'olive',
      'Coriandre fraîche',
      'Sel, poivre, piment d\'Espelette',
    ],
    steps: [
      'Décortiquez les crevettes et coupez-les en deux.',
      'Pressez les citrons verts.',
      'Coupez l\'avocat et la mangue en petits dés.',
      'Hachez finement l\'échalote.',
      'Ciseliez la coriandre fraîche.',
      'Mélangez tous les ingrédients dans un bol.',
      'Arrosez de jus de citron vert et d\'huile d\'olive.',
      'Assaisonnez et laissez mariner 15 minutes au frais.',
      'Servez dans des verrines avec une feuille de coriandre.',
    ],
  },
  {
    id: 'aperitif-08',
    title: 'Bouchées apéritives au chèvre et miel',
    description: 'Des feuilletés au chèvre et au miel, croustillants et gourmands.',
    prepTimeMin: 15,
    cookTimeMin: 15,
    servings: 8,
    difficulty: 'facile',
    tags: ['chèvre', 'miel', 'feuilleté', 'apéritif'],
    ingredients: [
      '1 pâte feuilletée',
      '200 g de fromage de chèvre frais',
      '3 cuillères à soupe de miel',
      '1 cuillère à soupe de thym frais',
      'Noix concassées',
      'Poivre',
    ],
    steps: [
      'Préchauffez le four à 200 degrés.',
      'Étalez la pâte feuilletée et découpez des rectangles.',
      'Coupez le chèvre en tranches.',
      'Disposez le chèvre sur chaque rectangle de pâte.',
      'Arrosez d\'un filet de miel.',
      'Parsemez de thym et de noix concassées.',
      'Poivrez légèrement.',
      'Roulez ou repliez la pâte.',
      'Enfournez 15 minutes jusqu\'à dorure et servez chaud.',
    ],
  },

  // ═══════════════════════════════════════════
  // PETITS-DÉJEUNERS / BRUNCH (7)
  // ═══════════════════════════════════════════

  {
    id: 'pdj-01',
    title: 'Crêpes bretonnes',
    description: 'Des crêpes fines et légères, sucrées ou salées.',
    prepTimeMin: 10,
    cookTimeMin: 20,
    servings: 6,
    difficulty: 'facile',
    tags: ['crêpes', 'breton', 'classique', 'brunch'],
    ingredients: [
      '250 g de farine',
      '4 œufs',
      '500 ml de lait',
      '50 g de beurre fondu',
      '1 cuillère à soupe de sucre',
      '1 pincée de sel',
      'Beurre pour la cuisson',
    ],
    steps: [
      'Mélangez la farine, le sucre et le sel dans un grand bol.',
      'Creusez un puits et ajoutez les œufs.',
      'Versez le lait progressivement en fouettant.',
      'Ajoutez le beurre fondu.',
      'Laissez reposer la pâte 30 minutes au réfrigérateur.',
      'Faites chauffer une poêle beurrée.',
      'Versez une louche de pâte et faites tourner la poêle.',
      'Cuisez 1 minute de chaque côté.',
      'Servez avec sucre, confiture, Nutella ou garniture salée.',
    ],
  },
  {
    id: 'pdj-02',
    title: 'Pain perdu',
    description: 'Des tranches de pain trempées dans un mélange aux œufs et cuites au beurre.',
    prepTimeMin: 10,
    cookTimeMin: 15,
    servings: 4,
    difficulty: 'facile',
    tags: ['pain', 'œuf', 'classique', 'brunch'],
    ingredients: [
      '8 tranches de pain rassis',
      '3 œufs',
      '200 ml de lait',
      '50 g de sucre',
      '1 cuillère à café d\'extrait de vanille',
      'Beurre pour la cuisson',
      'Sucre glace, sirop d\'érable ou fruits frais',
    ],
    steps: [
      'Battez les œufs avec le sucre et la vanille.',
      'Ajoutez le lait et mélangez bien.',
      'Trempez les tranches de pain dans le mélange.',
      'Laissez-les bien imbiber des deux côtés.',
      'Faites fondre le beurre dans une poêle.',
      'Faites dorer les tranches 2 minutes de chaque côté.',
      'Égouttez sur du papier absorbant.',
      'Servez chaud saupoudré de sucre glace.',
      'Accompagnez de sirop d\'érable ou de fruits frais.',
    ],
  },
  {
    id: 'pdj-03',
    title: 'Pancakes moelleux',
    description: 'Des pancakes épais et moelleux, parfaits pour un brunch gourmand.',
    prepTimeMin: 10,
    cookTimeMin: 15,
    servings: 4,
    difficulty: 'facile',
    tags: ['pancakes', 'brunch', 'moelleux', 'américain'],
    ingredients: [
      '200 g de farine',
      '2 œufs',
      '200 ml de lait',
      '2 cuillères à soupe de sucre',
      '1 sachet de levure chimique',
      '1 pincée de sel',
      'Beurre pour la cuisson',
      'Sirop d\'érable, fruits, chocolat',
    ],
    steps: [
      'Mélangez la farine, le sucre, la levure et le sel.',
      'Creusez un puits et ajoutez les œufs.',
      'Versez le lait progressivement en mélangeant.',
      'Ne pas trop mélanger: quelques grumeaux sont normaux.',
      'Faites chauffer une poêle beurrée à feu moyen.',
      'Versez une louche de pâte.',
      'Quand des bulles apparaissent, retournez le pancake.',
      'Cuisez 1 minute de plus de l\'autre côté.',
      'Servez empilés avec du sirop d\'érable et des fruits.',
    ],
  },
  {
    id: 'pdj-04',
    title: 'Granola maison aux fruits secs',
    description: 'Un granola croustillant fait maison aux noix et miel.',
    prepTimeMin: 10,
    cookTimeMin: 30,
    servings: 8,
    difficulty: 'facile',
    tags: ['granola', 'céréales', 'noix', 'sain'],
    ingredients: [
      '300 g de flocons d\'avoine',
      '100 g de noix mélangées',
      '80 g de miel',
      '50 ml d\'huile d\'olive',
      '50 g de raisins secs',
      '2 cuillères à soupe de graines de sésame',
      '1 cuillère à café de cannelle',
      '1 pincée de sel',
    ],
    steps: [
      'Préchauffez le four à 160 degrés.',
      'Mélangez les flocons d\'avoine avec les noix concassées.',
      'Ajoutez les graines de sésame et la cannelle.',
      'Faites chauffer le miel avec l\'huile.',
      'Versez le mélange liquide sur les flocons.',
      'Mélangez bien pour tout enrober.',
      'Étalez sur une plaque recouverte de papier cuisson.',
      'Enfournez 25 minutes en remuant à mi-cuisson.',
      'Laissez refroidir avant d\'ajouter les raisins secs.',
    ],
  },
  {
    id: 'pdj-05',
    title: 'Œufs brouillés à la française',
    description: 'Des œufs brouillés crémeux et fondants, cuisinés à feu très doux.',
    prepTimeMin: 5,
    cookTimeMin: 10,
    servings: 2,
    difficulty: 'facile',
    tags: ['œuf', 'crémeux', 'classique', 'rapide'],
    ingredients: [
      '4 œufs frais',
      '30 g de beurre',
      '2 cuillères à soupe de crème fraîche',
      'Sel, poivre',
      'Ciboulette fraîche',
      'Toast de pain de mie',
    ],
    steps: [
      'Cassez les œufs dans un bol et battez-les légèrement.',
      'Faites fondre le beurre dans une poêle à feu très doux.',
      'Versez les œufs dans la poêle.',
      'Remuez lentement avec une spatule en bois.',
      'Retirez du feu quand les œufs sont encore crémeux.',
      'Ajoutez la crème fraîche hors du feu.',
      'Assaisonnez avec le sel et le poivre.',
      'Parsemez de ciboulette ciselée.',
      'Servez immédiatement sur des toasts beurrés.',
    ],
  },
  {
    id: 'pdj-06',
    title: 'Smoothie bowl aux fruits rouges',
    description: 'Un bol de smoothie épais garni de fruits, graines et granola.',
    prepTimeMin: 10,
    cookTimeMin: 0,
    servings: 2,
    difficulty: 'facile',
    tags: ['smoothie', 'fruits', 'sain', 'brunch'],
    ingredients: [
      '300 g de fruits rouges surgelés',
      '1 banane',
      '100 ml de lait d\'amande',
      'Granola maison',
      'Graines de chia',
      'Noix de coco râpée',
      'Miel',
    ],
    steps: [
      'Mettez les fruits rouges surgelés dans le mixeur.',
      'Ajoutez la banane coupée en morceaux.',
      'Versez le lait d\'amande.',
      'Mixez jusqu\'à obtenir une texture épaisse.',
      'Versez dans deux bols.',
      'Disposez les garnitures sur le dessus.',
      'Ajoutez le granola, les graines de chia et la coco.',
      'Arrosez d\'un filet de miel.',
      'Servez immédiatement bien froid.',
    ],
  },
  {
    id: 'pdj-07',
    title: 'Tartines au fromage et confiture',
    description: 'Des tartines gourmandes de fromage et confiture pour un brunch élégant.',
    prepTimeMin: 10,
    cookTimeMin: 5,
    servings: 4,
    difficulty: 'facile',
    tags: ['fromage', 'confiture', 'tartine', 'brunch'],
    ingredients: [
      '4 tranches de pain de campagne',
      '200 g de fromage (brie, comté, chèvre)',
      'Confiture de figues ou d\'abricot',
      'Noix concassées',
      'Miel',
      'Roquette',
    ],
    steps: [
      'Faites griller les tranches de pain.',
      'Coupez le fromage en tranches.',
      'Tartinez les tartines de confiture.',
      'Disposez les tranches de fromage sur la confiture.',
      'Parsemez de noix concassées.',
      'Arrosez d\'un filet de miel.',
      'Ajoutez quelques feuilles de roquette.',
      'Passez au four 3 minutes pour faire fondre le fromage.',
      'Servez chaud pour un brunch savoureux.',
    ],
  },
];

// ─── Fun Facts ──────────────────────────────────────────

export const FUN_FACTS: string[] = [
  "Le saviez-vous ? Le croissant a été inventé à Vienne, pas en France !",
  "Le mot restaurant vient du verbe restaurer, car les premiers servaient des bouillons restauratifs.",
  "La France produit plus de 1 000 variétés de fromage, soit environ une par jour de l'année.",
  "La tour Eiffel peut grandir de 15 centimètres en été à cause de la chaleur.",
  "Les chats passent environ 70 pourcent de leur vie à dormir.",
  "Le miel ne périt jamais. On en a trouvé des pots comestibles dans des tombes égyptiennes vieilles de 3 000 ans.",
  "La baguette de pain telle qu'on la connaît date seulement de 1920.",
  "Un escargot peut dormir pendant trois ans d'affilée.",
  "Le Mont-Saint-Michel reçoit environ 3 millions de visiteurs par an.",
  "Les fraises ne sont pas des fruits, mais des faux-fruits. Les vrais fruits sont les petits grains à la surface.",
  "La langue française compte environ 100 000 mots, mais on en utilise couramment moins de 2 000.",
  "Le champagne doit obligatoirement venir de la région éponyme pour porter ce nom.",
  "Les dauphins dorment d'un œil ouvert pour surveiller les prédateurs.",
  "Le ballet a été inventé en Italie au XVe siècle avant de devenir populaire en France.",
  "Un rein humain filtre environ 180 litres de sang par jour.",
  "Le musée du Louvre contient environ 380 000 objets, mais seule une partie est exposée.",
  "Les pieuvres ont trois cœurs et du sang bleu.",
  "La gare de Paris-Nord a été le théâtre du plus grand vol de train de l'histoire en 1895.",
  "Le chocolat contient une substance appelée théobromine qui est toxique pour les chiens.",
  "La coccinelle peut manger jusqu'à 5 000 pucerons au cours de sa vie.",
  "Le canal de la Sambra à l'Oise permet de relier l'Escaut à la Seine par voie d'eau.",
  "Le premier restaurant étoilé Guide Michelin coûtait 1 franc le menu en 1900.",
  "L'eau constitue environ 60 pourcent du corps humain adulte.",
  "La Bastille n'a été détruite qu'un an après la Révolution, en 1790.",
  "Les flamants roses sont rose à cause des crevettes qu'ils mangent.",
  "En France, il existe plus de 400 variétés de pommes différentes.",
  "La lumière du Soleil met environ 8 minutes pour atteindre la Terre.",
  "Le coquelicot est le symbole de la mémoire des soldats depuis la Première Guerre mondiale.",
  "Les abeilles communiquent entre elles en dansant.",
  "Le plus long mot de la langue française est anticonstitutionnellement, avec 25 lettres.",
];

// ─── Jokes ──────────────────────────────────────────────

export const JOKES: string[] = [
  "Que dit un citron quand il fait un braquage ? « Pas un zeste ! »",
  "Pourquoi les plongeurs plongent-ils toujours en arrière et jamais en avant ? Parce que sinon, ils tomberaient dans le bateau.",
  "Que fait une fraise sur un cheval ? Tagada tagada !",
  "Quel est le comble pour un électricien ? De ne pas être au courant.",
  "Comment appelle-t-on un chat tombé dans un pot de peinture le jour de Noël ? Un chat peint de Noël !",
  "Que dit un oignon quand il se cogne ? Ah, j'ai mal aux yeux !",
  "Pourquoi les moutons aiment-ils le chewing-gum ? Parce que c'est bon pour la laine.",
  "Quelle est la différence entre un héros et un zéro ? La première lettre du mot !",
  "Que fait un escargot quand il traverse l'autoroute ? Il slalome !",
  "Pourquoi le livre de mathématiques est-il triste ? Parce qu'il a trop de problèmes.",
  "Comment dit-on maman-chat en anglais ? Mother furrer.",
  "Que se disent deux flocons de neige ? « Ça glisse de travers ! »",
  "Pourquoi les fantômes aiment-ils les ascenseurs ? Parce que ça les soulève l'esprit.",
  "Quel est le sport préféré des insectes ? Le criquet.",
  "Que fait un canif dans un pressing ? Il se fait repasser.",
  "C'est l'histoire d'un pingouin qui respire par les fesses. Un jour il s'assoit et il meurt.",
  "Pourquoi le gâteau est-il triste ? Parce qu'il est en train de trancher.",
  "Que dit un timbre quand on l'écrase ? « Ooooh la la, quelle pression ! »",
  "Pourquoi les oiseaux ne se servent-ils pas de Facebook ? Parce qu'ils ont déjà Twitter.",
  "Comment appelle-t-on un chien magicien ? Un labracadabrador !",
];

// ─── Quotes ─────────────────────────────────────────────

export const QUOTES: string[] = [
  "La vie est un mystère qu'il faut vivre, et non un problème à résoudre. — Gandhi",
  "Le succès, c'est d'aller d'échec en échec sans perdre son enthousiasme. — Winston Churchill",
  "La seule façon de faire du bon travail est d'aimer ce que vous faites. — Steve Jobs",
  "L'imagination est plus importante que le savoir. — Albert Einstein",
  "Dans la vie, on ne fait pas ce que l'on veut mais on est responsable de ce que l'on est. — Jean-Paul Sartre",
  "Il faut imaginer Sisyphe heureux. — Albert Camus",
  "Le bonheur est parfois caché dans l'inconnu. — Victor Hugo",
  "Chaque homme doit inventer son propre chemin. — Paul Gauguin",
  "La liberté commence là où l'ignorance finit. — Victor Hugo",
  "Il n'y a qu'une façon d'échouer, c'est d'abandonner avant d'avoir réussi. — Georges Clemenceau",
  "La créativité, c'est l'intelligence qui s'amuse. — Albert Einstein",
  "Le meilleur moment pour planter un arbre était il y a 20 ans. Le deuxième meilleur moment est maintenant. — Proverbe chinois",
  "Nous ne voyons pas les choses telles qu'elles sont, mais telles que nous sommes. — Anaïs Nin",
  "Le courage n'est pas l'absence de peur, mais la capacité de la vaincre. — Nelson Mandela",
  "La simplicité est la sophistication suprême. — Léonard de Vinci",
  "Un voyage de mille lieues commence toujours par un premier pas. — Lao Tseu",
  "Le seul vrai voyage est celui qu'on fait avec les yeux fermés. — Marcel Proust",
  "Rien n'est plus dangereux qu'une idée quand on n'a qu'une seule idée. — Alain",
  "La musique exprime ce qui ne peut être dit et sur quoi il est impossible de rester silencieux. — Victor Hugo",
  "Ce qui ne te tue pas te rend plus fort. — Friedrich Nietzsche",
];

// ─── Greetings ──────────────────────────────────────────

export const MORNING_GREETINGS = {
  sunny: [
    "Bonjour ! Le soleil brille aujourd'hui, c'est une belle journée qui s'annonce !",
    "Bonjour ! Il fait magnifique dehors, profitez-en bien !",
    "Bonjour ! Une journée ensoleillée vous attend, comment puis-je vous aider ?",
  ],
  rainy: [
    "Bonjour ! Il pleut un peu ce matin. Parfait pour rester au chaud !",
    "Bonjour ! La pluie arrose le jardin. Que puis-je faire pour vous ?",
    "Bonjour ! Météo pluvieuse aujourd'hui. Un bon café et je suis à votre écoute !",
  ],
  cold: [
    "Bonjour ! Il fait frais ce matin, n'oubliez pas votre manteau !",
    "Bonjour ! Températures basses aujourd'hui, restez au chaud !",
    "Bonjour ! L'air est vif ce matin. Puis-je vous préparer quelque chose de réconfortant ?",
  ],
  hot: [
    "Bonjour ! Chaleur aujourd'hui, pensez à bien vous hydrater !",
    "Bonjour ! Il fait chaud ce matin, restez au frais !",
    "Bonjour ! Belle journée chaude en vue. Un verre d'eau fraîche vous ferait du bien !",
  ],
  cloudy: [
    "Bonjour ! Le ciel est couvert ce matin, mais la journée est à vous !",
    "Bonjour ! Ciel nuageux aujourd'hui. Comment puis-je vous accompagner ?",
    "Bonjour ! Temps couvert, parfait pour une journée tranquille à l'intérieur !",
  ],
  snowy: [
    "Bonjour ! Il neige ce matin, quel paysage magique !",
    "Bonjour ! Les flocons tombent doucement, restez bien au chaud !",
    "Bonjour ! Journée de neige aujourd'hui. Profitez-en depuis l'intérieur !",
  ],
  default: [
    "Bonjour ! Comment puis-je vous aider ce matin ?",
    "Bonjour ! Je suis là pour vous accompagner aujourd'hui.",
    "Bonjour ! Quelle belle journée à vivre ensemble !",
  ],
};

export const EVENING_GREETINGS = {
  sunny: [
    "Bonsoir ! Quelle belle journée ensoleillée ! Que puis-je faire pour vous ?",
    "Bonsoir ! Le soleil se couche sur une belle journée. Comment puis-je vous aider ?",
    "Bonsoir ! Lumière dorée ce soir. Un moment agréable pour se détendre !",
  ],
  rainy: [
    "Bonsoir ! La pluie tambourine doucement. Parfait pour une soirée tranquille !",
    "Bonsoir ! Bruit de pluie ce soir. Un bon repas chaud et un film, ça vous dit ?",
    "Bonsoir ! Temps humide dehors, mais au chaud ici, tout va bien !",
  ],
  cold: [
    "Bonsoir ! Il fait froid ce soir, restez bien au chaud !",
    "Bonsoir ! Soirée fraîche, un thé ou un chocolat chaud vous ferait du bien !",
    "Bonsoir ! Températures basses ce soir. Puis-je vous réchauffer avec quelque chose ?",
  ],
  hot: [
    "Bonsoir ! Chaleur persistante ce soir, pensez à vous rafraîchir !",
    "Bonsoir ! Nuit chaude en vue. Un ventilateur ou une boisson fraîche ?",
    "Bonsoir ! L'air est encore lourd ce soir. Rien de tel qu'une douche fraîche !",
  ],
  cloudy: [
    "Bonsoir ! Ciel couvert ce soir, mais l'intérieur est si chaleureux !",
    "Bonsoir ! Soirée calme. Comment puis-je rendre votre soirée agréable ?",
    "Bonsoir ! Nuit nuageuse en vue. Que puis-je faire pour vous ce soir ?",
  ],
  snowy: [
    "Bonsoir ! Il neige ce soir, quel spectacle depuis la fenêtre !",
    "Bonsoir ! Soirée enneigée, restez bien au chaud chez vous !",
    "Bonsoir ! Les flocons dansent ce soir. Un moment de paix et de beauté !",
  ],
  default: [
    "Bonsoir ! Que puis-je faire pour vous ce soir ?",
    "Bonsoir ! Je suis là pour vous accompagner cette soirée.",
    "Bonsoir ! Une bonne soirée à vous. Comment puis-je vous être utile ?",
  ],
} as const;

// Type helpers for greeting weather keys
export type GreetingWeatherKey = keyof typeof MORNING_GREETINGS;
