// ═══════════════════════════════════════════════════════
// MAISON CONSCIENTE — Application Constants
// RSS sources, local recipes, fun facts, jokes, quotes
// ═══════════════════════════════════════════════════════

export interface RssSource {
  id: string;
  name: string;
  url: string;
  category: 'general' | 'sport' | 'culture' | 'tech' | 'economy' | 'health' | 'local' | 'horoscope';
  refreshIntervalMin: number;
  active: boolean;
}

export interface LocalRecipe {
  id: string;
  title: string;
  description: string;
  difficulty: 'Facile' | 'Moyen' | 'Difficile';
  prepTimeMin: number;
  cookTimeMin: number;
  servings: number;
  ingredients: string[];
  steps: string[];
  tags: string[];
}

/* ═══ RSS SOURCES ═══ */
export const RSS_SOURCES: RssSource[] = [
  { id: 'franceinfo', name: 'France Info', url: 'https://www.francetvinfo.fr/top-info.rss', category: 'general', refreshIntervalMin: 30, active: true },
  { id: 'lemonde', name: 'Le Monde', url: 'https://www.lemonde.fr/rss/une.xml', category: 'general', refreshIntervalMin: 30, active: true },
  { id: 'lefigaro', name: 'Le Figaro', url: 'https://www.lefigaro.fr/rss/figaro_actualites.xml', category: 'general', refreshIntervalMin: 30, active: true },
  { id: 'franceculture', name: 'France Culture', url: 'https://radiofrance-podcast.net/podcast09/rss_14307.xml', category: 'culture', refreshIntervalMin: 60, active: false },
  { id: 'equipe', name: "L'Équipe", url: 'https://www.lequipe.fr/rss/actu_rss.xml', category: 'sport', refreshIntervalMin: 30, active: false },
  { id: 'numerama', name: 'Numerama', url: 'https://www.numerama.com/rss/news.rss', category: 'tech', refreshIntervalMin: 60, active: false },
  { id: 'leshoroscope', name: 'Mon Horoscope du Jour', url: 'https://www.mon-horoscope-du-jour.com/rss-horoscope-gratuit.php', category: 'horoscope', refreshIntervalMin: 360, active: true },
  { id: 'routard', name: 'Le Routard', url: 'https://www.routard.com/rss/rss_actualites.xml', category: 'culture', refreshIntervalMin: 120, active: false },
];

/* ═══ 50 LOCAL RECIPES ═══ */
export const LOCAL_RECIPES: LocalRecipe[] = [
  // --- ENTRÉES ---
  { id: 'r01', title: 'Soupe à l\'oignon gratinée', description: 'Un classique réconfortant de la cuisine française avec du fromage fondu.', difficulty: 'Facile', prepTimeMin: 15, cookTimeMin: 40, servings: 4, ingredients: ['6 oignons jaunes', '50g de beurre', '1 cuillère à soupe de sucre', '1L de bouillon de bœuf', '200ml de vin blanc', '4 tranches de pain de campagne', '200g de gruyère râpé', 'Sel et poivre'], steps: ['Émincez finement les oignons.', 'Faites fondre le beurre dans une grande casserole à feu moyen.', 'Ajoutez les oignons et le sucre. Faites caraméliser pendant 25 minutes en remuant.', 'Déglacez au vin blanc, puis ajoutez le bouillon. Portez à ébullition.', 'Laissez mijoter 15 minutes à feu doux.', 'Préchauffez le four à 200°C.', 'Versez la soupe dans des bols allant au four.', 'Déposez les tranches de pain et le gruyère râpé.', 'Gratinez au four pendant 10 minutes jusqu\'à dorure.'], tags: ['entrée', 'réconfortant', 'hiver', 'classique'] },
  { id: 'r02', title: 'Quiche lorraine', description: 'La quiche emblématique au lard fumé et aux œufs.', difficulty: 'Facile', prepTimeMin: 20, cookTimeMin: 35, servings: 6, ingredients: ['1 pâte brisée', '200g de lardons fumés', '3 œufs', '200ml de crème fraîche', '200ml de lait', '100g de gruyère râpé', 'Sel, poivre, muscade'], steps: ['Préchauffez le four à 180°C.', 'Étalez la pâte brisée dans un moule à tarte beurré.', 'Faites dorer les lardons à la poêle sans matière grasse.', 'Dans un saladier, battez les œufs avec la crème et le lait.', 'Ajoutez le sel, le poivre et une pincée de muscade.', 'Répartissez les lardons sur la pâte.', 'Versez l\'appareil sur les lardons et parsemez de gruyère.', 'Enfournez 35 minutes jusqu\'à dorure.'], tags: ['entrée', 'classique', 'français', 'fromage'] },
  { id: 'r03', title: 'Salade niçoise', description: 'La salade méditerranéenne complète et colorée.', difficulty: 'Facile', prepTimeMin: 20, cookTimeMin: 0, servings: 4, ingredients: ['4 tomates', '2 poivrons', '1 concombre', '200g de thon en boîte', '4 œufs durs', '100g d\'olives noires', '2 anchois', '1 oignon nouveau', '4 cuillères à soupe d\'huile d\'olive', '2 cuillères à soupe de vinaigre', 'Basilic frais'], steps: ['Coupez les tomates en quartiers et les poivrons en lanières.', 'Émincez le concombre et l\'oignon nouveau.', 'Écalez les œufs durs et coupez-les en deux.', 'Disposez tous les légumes sur un grand plat.', 'Émiettez le thon et ajoutez les olives et les anchois.', 'Préparez la vinaigrette avec l\'huile, le vinaigre, sel et poivre.', 'Nappez la salade et décorez de basilic frais.'], tags: ['salade', 'frais', 'méditerranéen', 'rapide'] },
  { id: 'r04', title: 'Velouté de potimarron', description: 'Un velouté onctueux et doux pour l\'automne.', difficulty: 'Facile', prepTimeMin: 15, cookTimeMin: 25, servings: 4, ingredients: ['1 potimarron (environ 800g)', '1 oignon', '2 gousses d\'ail', '500ml de bouillon de légumes', '100ml de crème fraîche', '1 cuillère à soupe d\'huile d\'olive', 'Graines de courge torréfiées', 'Sel et poivre'], steps: ['Coupez le potimarron en morceaux et épépinez-le.', 'Émincez l\'oignon et hachez l\'ail.', 'Faites revenir l\'oignon et l\'ail dans l\'huile d\'olive.', 'Ajoutez le potimarron et le bouillon.', 'Portez à ébullition, puis laissez mijoter 20 minutes.', 'Mixez finement au blender ou au mixeur plongeant.', 'Ajoutez la crème, salez et poivrez.', 'Servez avec des graines de courge torréfiées.'], tags: ['soupe', 'automne', 'végétarien', 'onctueux'] },
  { id: 'r05', title: 'Bruschetta à la tomate', description: 'L\'apéritif italien classique et frais.', difficulty: 'Facile', prepTimeMin: 10, cookTimeMin: 5, servings: 4, ingredients: ['8 tranches de pain de campagne', '4 tomates mûres', '2 gousses d\'ail', 'Feuilles de basilic', '3 cuillères à soupe d\'huile d\'olive', '1 cuillère à soupe de vinaigre balsamique', 'Sel et poivre'], steps: ['Coupez les tomates en petits dés.', 'Hachez le basilic et mélangez avec les tomates.', 'Ajoutez l\'huile d\'olive, le vinaigre, sel et poivre.', 'Faites griller les tranches de pain au four ou à la poêle.', 'Frottez les tartines avec la gousse d\'ail coupée en deux.', 'Déposez le mélange tomate-basilic sur le pain.', 'Servez immédiatement.'], tags: ['apéritif', 'italien', 'frais', 'rapide'] },
  { id: 'r06', title: 'Pâté en croûte', description: 'Un pâté rustique avec pâte feuilletée et farce savoureuse.', difficulty: 'Difficile', prepTimeMin: 30, cookTimeMin: 45, servings: 8, ingredients: ['1 pâte feuilletée', '300g de viande hachée (porc et veau)', '100g de champignons', '2 échalotes', '1 œuf', '50ml de crème', '1 cuillère à café de thym', 'Sel, poivre, muscade', '1 jaune d\'œuf pour dorer'], steps: ['Hachez finement les échalotes et les champignons.', 'Faites revenir les champignons et échalotes 5 minutes.', 'Mélangez la viande hachée avec les champignons, la crème, l\'œuf et les épices.', 'Abaissez la moitié de la pâte dans un moule à cake.', 'Garnissez avec la farce en tassant bien.', 'Couvrez avec le reste de la pâte et soudez les bords.', 'Dorez au jaune d\'œuf et piquez le dessus.', 'Enfournez à 200°C pendant 45 minutes.'], tags: ['entrée', 'rustique', 'festif', 'français'] },

  // --- PLATS PRINCIPAUX ---
  { id: 'r07', title: 'Coq au vin', description: 'Le grand classique de la cuisine française au vin rouge.', difficulty: 'Moyen', prepTimeMin: 25, cookTimeMin: 120, servings: 6, ingredients: ['1 coq ou 8 cuisses de poulet', '1 bouteille de vin rouge', '200g de lardons', '200g de champignons de Paris', '3 carottes', '2 oignons', '3 gousses d\'ail', '50g de beurre', '2 cuillères à soupe de farine', 'Bouquet garni', 'Sel et poivre'], steps: ['Coupez le poulet en morceaux et faites-le dorer au beurre.', 'Retirez la viande et faites revenir les lardons.', 'Ajoutez les carottes en rondelles, les oignons émincés et l\'ail.', 'Saupoudrez de farine et remuez.', 'Versez le vin rouge et ajoutez le bouquet garni.', 'Remettez le poulet et portez à ébullition.', 'Baissez le feu et laissez mijoter 2h à couvert.', 'Ajoutez les champignons 20 minutes avant la fin.'], tags: ['plat', 'classique', 'français', 'vin', 'mijoté'] },
  { id: 'r08', title: 'Gratin dauphinois', description: 'Le gratin de pommes de terre crémeux et gratiné.', difficulty: 'Facile', prepTimeMin: 20, cookTimeMin: 60, servings: 6, ingredients: ['1kg de pommes de terre', '300ml de crème fraîche', '300ml de lait', '2 gousses d\'ail', '50g de beurre', '100g de gruyère râpé', 'Muscade', 'Sel et poivre'], steps: ['Préchauffez le four à 180°C.', 'Épluchez et coupez les pommes de terre en fines rondelles.', 'Frottez un plat à gratin avec l\'ail coupé en deux.', 'Beurrez le plat.', 'Disposez les rondelles de pommes de terre en couches.', 'Faites chauffer la crème et le lait avec la muscade, sel et poivre.', 'Versez sur les pommes de terre.', 'Parsemez de gruyère et enfournez 60 minutes.'], tags: ['plat', 'gratin', 'classique', 'fromage', 'végétarien'] },
  { id: 'r09', title: 'Blanquette de veau', description: 'Le ragoût blanc et onctueux de veau aux carottes.', difficulty: 'Moyen', prepTimeMin: 20, cookTimeMin: 90, servings: 6, ingredients: ['800g de veau (épaule ou collier)', '3 carottes', '2 poireaux', '2 oignons', '1 bouquet garni', '50g de beurre', '30g de farine', '200ml de crème fraîche', '2 jaunes d\'œufs', 'Champignons', 'Citron', 'Sel et poivre'], steps: ['Coupez le veau en morceaux et blanchissez-le 5 minutes à l\'eau bouillante.', 'Égouttez et rincez.', 'Dans une cocotte, faites fondre le beurre et ajoutez la viande.', 'Ajoutez les carottes, poireaux, oignons et bouquet garni.', 'Recouvrez d\'eau et portez à ébullition. Laissez mijoter 1h30.', 'Retirez la viande et les légumes.', 'Faites un roux avec le beurre et la farine, mouillez avec le bouillon filtré.', 'Ajoutez la crème et les jaunes d\'œufs hors du feu. Servez avec du citron.'], tags: ['plat', 'classique', 'français', 'mijoté', 'crémeux'] },
  { id: 'r10', title: 'Ratatouille provençale', description: 'Le ragoût de légumes du soleil de Provence.', difficulty: 'Facile', prepTimeMin: 20, cookTimeMin: 45, servings: 4, ingredients: ['2 courgettes', '2 aubergines', '4 tomates', '2 poivrons', '1 oignon', '3 gousses d\'ail', 'Herbes de Provence', '4 cuillères à soupe d\'huile d\'olive', 'Sel et poivre'], steps: ['Coupez tous les légumes en cubes réguliers.', 'Faites revenir l\'oignon et l\'ail dans l\'huile d\'olive.', 'Ajoutez les poivrons et laissez cuire 5 minutes.', 'Ajoutez les aubergines et les courgettes.', 'Mélangez bien et laissez cuire 10 minutes.', 'Ajoutez les tomates concassées et les herbes.', 'Laissez mijoter 30 minutes à feu doux à couvert.', 'Rectifiez l\'assaisonnement et servez chaud ou froid.'], tags: ['plat', 'végétarien', 'méditerranéen', 'été', 'santé'] },
  { id: 'r11', title: 'Bœuf bourguignon', description: 'Le ragoût emblématique au vin de Bourgogne.', difficulty: 'Moyen', prepTimeMin: 25, cookTimeMin: 150, servings: 6, ingredients: ['800g de bœuf (paleron ou gîte)', '1 bouteille de vin rouge', '200g de lardons', '250g de champignons', '3 carottes', '2 oignons', '2 échalotes', '50g de farine', 'Bouquet garni', 'Sel et poivre'], steps: ['Coupez le bœuf en gros cubes et farinez-les.', 'Faites dorer les morceaux dans une cocotte chaude.', 'Retirez et faites revenir les lardons.', 'Ajoutez les carottes et oignons émincés.', 'Remettez la viande, versez le vin rouge.', 'Ajoutez le bouquet garni et portez à ébullition.', 'Couvrez et laissez mijoter 2h30 à feu très doux.', 'Ajoutez les champignons 20 minutes avant la fin.'], tags: ['plat', 'classique', 'français', 'vin', 'mijoté', 'festif'] },
  { id: 'r12', title: 'Croque-monsieur', description: 'Le croque chaud au jambon et fromage fondu.', difficulty: 'Facile', prepTimeMin: 10, cookTimeMin: 10, servings: 2, ingredients: ['4 tranches de pain de mie', '4 tranches de jambon blanc', '100g de gruyère râpé', '2 cuillères à soupe de béchamel', 'Beurre', 'Sel et poivre'], steps: ['Préchauffez le four à 200°C.', 'Tartinez les tranches de pain de béchamel.', 'Déposez le jambon et le gruyère sur 2 tranches.', 'Refermez avec les 2 autres tranches, béchamel à l\'intérieur.', 'Beurrez le dessus.', 'Enfournez 10 minutes jusqu\'à dorure.', 'Servez chaud avec une salade verte.'], tags: ['plat', 'rapide', 'classique', 'fromage', 'enfants'] },
  { id: 'r13', title: 'Poulet rôti aux herbes', description: 'Un poulet juteux parfumé au thym et romarin.', difficulty: 'Facile', prepTimeMin: 15, cookTimeMin: 75, servings: 4, ingredients: ['1 poulet entier (1.5kg)', '3 gousses d\'ail', 'Thym frais', 'Romarin frais', '4 cuillères à soupe d\'huile d\'olive', '1 citron', '500g de pommes de terre', 'Sel et poivre'], steps: ['Préchauffez le four à 200°C.', 'Séchez le poulet et frottez-le d\'huile d\'olive.', 'Insérez le citron coupé en deux et l\'ail dans la cavité.', 'Farcissez avec le thym et le romarin.', 'Assaisonnez généreusement de sel et poivre.', 'Entourez de pommes de terre en quartiers.', 'Enfournez 1h15 en arrosant régulièrement du jus.', 'Laissez reposer 10 minutes avant de découper.'], tags: ['plat', 'rôti', 'classique', 'herbes', 'dimanche'] },
  { id: 'r14', title: 'Tartiflette savoyarde', description: 'Le gratin de pommes de terre au reblochon des montagnes.', difficulty: 'Facile', prepTimeMin: 15, cookTimeMin: 45, servings: 4, ingredients: ['1kg de pommes de terre', '1 reblochon (500g)', '200g de lardons', '1 oignon', '200ml de crème fraîche', '1 gousse d\'ail', 'Vin blanc', 'Sel et poivre'], steps: ['Préchauffez le four à 200°C.', 'Épluchez et coupez les pommes de terre en rondelles.', 'Faites-les précuire 10 minutes à la vapeur.', 'Faites dorer les lardons et l\'oignon émincé.', 'Frottez un plat à gratin avec l\'ail.', 'Disposez une couche de pommes de terre, les lardons, la crème.', 'Coupez le reblochon en deux et déposez-le sur le dessus.', 'Enfournez 35 minutes jusqu\'à dorure.'], tags: ['plat', 'montagne', 'fromage', 'hiver', 'réconfortant'] },
  { id: 'r15', title: 'Pâtes carbonara', description: 'Les spaghettis crémeux à la romaine au guanciale.', difficulty: 'Facile', prepTimeMin: 10, cookTimeMin: 15, servings: 4, ingredients: ['400g de spaghetti', '150g de guanciale ou lardons', '4 jaunes d\'œufs', '50g de pecorino romano', 'Poivre noir', 'Sel (pour l\'eau des pâtes)'], steps: ['Faites cuire les spaghetti al dente dans l\'eau salée.', 'Coupez le guanciale en bâtonnets et faites-le dorer sans matière grasse.', 'Dans un bol, battez les jaunes avec le pecorino râpé.', 'Égouttez les pâtes en réservant une louche d\'eau de cuisson.', 'Hors du feu, versez les pâtes dans la poêle avec le guanciale.', 'Ajoutez le mélange œufs-fromage et un filet d\'eau de cuisson.', 'Mélangez vivement pour créer une crème onctueuse.', 'Servez immédiatement avec beaucoup de poivre.'], tags: ['plat', 'pâtes', 'italien', 'rapide', 'crémeux'] },
  { id: 'r16', title: 'Curry de légumes au lait de coco', description: 'Un curry doux et parfumé aux légumes de saison.', difficulty: 'Facile', prepTimeMin: 15, cookTimeMin: 25, servings: 4, ingredients: ['1 patate douce', '2 carottes', '1 poivron', '100g de pois chiches', '400ml de lait de coco', '2 cuillères à soupe de pâte de curry', '1 oignon', '2 gousses d\'ail', 'Coriandre fraîche', 'Huile d\'olive'], steps: ['Coupez les légumes en morceaux.', 'Faites revenir l\'oignon et l\'ail dans l\'huile.', 'Ajoutez la pâte de curry et laissez cuire 2 minutes.', 'Ajoutez les légumes et les pois chiches.', 'Versez le lait de coco et portez à ébullition.', 'Laissez mijoter 20 minutes jusqu\'à tendreté.', 'Rectifiez l\'assaisonnement.', 'Servez avec du riz basmati et de la coriandre.'], tags: ['plat', 'végétarien', 'indien', 'exotique', 'santé'] },
  { id: 'r17', title: 'Steak frites', description: 'Le classique des brasseries françaises.', difficulty: 'Facile', prepTimeMin: 5, cookTimeMin: 20, servings: 2, ingredients: ['2 entrecôtes (300g chacune)', '600g de pommes de terre', 'Huile de friture', 'Beurre', 'Sel, poivre', 'Persil plat'], steps: ['Épluchez et coupez les pommes de terre en frites.', 'Faites-les précuire 5 minutes dans l\'huile à 140°C.', 'Sortez la viande du réfrigérateur 30 minutes avant cuisson.', 'Saisissez les entrecôtes 3 minutes de chaque côté à feu vif.', 'Baissez le feu et ajoutez le beurre pour arroser.', 'Finissez de cuire les frites à 180°C jusqu\'à dorure.', 'Égouttez les frites, salez et parsemez de persil.', 'Laissez reposer la viande 5 minutes avant de servir.'], tags: ['plat', 'classique', 'brasserie', 'français', 'rapide'] },
  { id: 'r18', title: 'Saumon en papillote', description: 'Un saumon fondant aux légumes et herbes.', difficulty: 'Facile', prepTimeMin: 10, cookTimeMin: 20, servings: 2, ingredients: ['2 pavés de saumon', '1 courgette', '1 carotte', '1 citron', '2 cuillères à soupe d\'huile d\'olive', 'Aneth frais', 'Sel et poivre'], steps: ['Préchauffez le four à 200°C.', 'Coupez les légumes en julienne.', 'Disposez les légumes au centre de deux grandes feuilles de papier sulfur.', 'Posez le saumon sur les légumes.', 'Arrosez d\'huile d\'olive, de jus de citron.', 'Assaisonnez sel, poivre et aneth.', 'Fermez hermétiquement les papillotes.', 'Enfournez 20 minutes. Ouvrez à table.'], tags: ['plat', 'poisson', 'santé', 'facile', 'rapide'] },
  { id: 'r19', title: 'Couscous royal', description: 'Le plat festif nord-africain aux 7 légumes.', difficulty: 'Moyen', prepTimeMin: 30, cookTimeMin: 90, servings: 8, ingredients: ['1kg de semoule', '500g d\'agneau', '200g de merguez', '2 navets', '2 carottes', '2 courgettes', '1 poivron', '1 potiron', '200g de pois chiches', 'Harissa', 'Raisins secs', 'Bouillon'], steps: ['Faites dorer l\'agneau en morceaux dans une cocotte.', 'Ajoutez les navets, carottes coupées et le bouillon.', 'Ajoutez la harissa selon votre goût.', 'Laissez mijoter 1h.', 'Ajoutez les courgettes, poivron et potiron.', 'Ajoutez les pois chiches et les merguez 20 min avant la fin.', 'Préparez la semoule en la vapeur en l\'arrosant d\'eau salée.', 'Servez avec des raisins secs et du bouillon à part.'], tags: ['plat', 'festif', 'nord-africain', 'mijoté', 'familial'] },
  { id: 'r20', title: 'Gratin de chou-fleur', description: 'Un gratin crémeux au chou-fleur et au fromage.', difficulty: 'Facile', prepTimeMin: 15, cookTimeMin: 35, servings: 4, ingredients: ['1 chou-fleur', '50g de beurre', '30g de farine', '400ml de lait', '100g de gruyère râpé', 'Muscade', 'Sel et poivre'], steps: ['Préchauffez le four à 180°C.', 'Divisez le chou-fleur en bouquets.', 'Faites cuire les bouquets 10 minutes à la vapeur.', 'Préparez une béchamel : faites fondre le beurre, ajoutez la farine, mouillez avec le lait.', 'Assaisonnez de muscade, sel et poivre.', 'Disposez le chou-fleur dans un plat à gratin.', 'Nappez de béchamel et parsemez de gruyère.', 'Enfournez 25 minutes.'], tags: ['plat', 'gratin', 'végétarien', 'fromage', 'hiver'] },

  // --- DESSERTS ---
  { id: 'r21', title: 'Crème brûlée', description: 'Le dessert onctueux à la croûte de caramel craquante.', difficulty: 'Moyen', prepTimeMin: 15, cookTimeMin: 45, servings: 4, ingredients: ['500ml de crème fraîche', '5 jaunes d\'œufs', '100g de sucre', '1 gousse de vanille', 'Cassonade pour le dessus'], steps: ['Préchauffez le four à 150°C.', 'Fendez la vanille et faites infuser dans la crème chaude.', 'Battez les jaunes avec le sucre sans mousser.', 'Versez la crème sur les jaunes en mélangeant.', 'Filtrez et versez dans des ramequins.', 'Enfournez au bain-marie 40 minutes.', 'Réfrigérez au moins 4 heures.', 'Avant de servir, parsemez de cassonade et caramélisez au chalumeau.'], tags: ['dessert', 'classique', 'français', 'onctueux'] },
  { id: 'r22', title: 'Mousse au chocolat', description: 'La mousse légère et intense au chocolat noir.', difficulty: 'Facile', prepTimeMin: 15, cookTimeMin: 0, servings: 4, ingredients: ['200g de chocolat noir', '4 œufs', '30g de sucre', '1 pincée de sel'], steps: ['Faites fondre le chocolat au bain-marie.', 'Séparez les blancs des jaunes.', 'Ajoutez les jaunes au chocolat fondu.', 'Battez les blancs en neige avec le sel.', 'Incorporez le sucre aux blancs.', 'Incorporez délicatement les blancs au chocolat.', 'Répartissez dans des verres.', 'Réfrigérez au moins 3 heures.'], tags: ['dessert', 'classique', 'chocolat', 'sans cuisson'] },
  { id: 'r23', title: 'Tarte tatin', description: 'La tarte aux pommes caramélisées à l\'envers.', difficulty: 'Moyen', prepTimeMin: 20, cookTimeMin: 40, servings: 8, ingredients: ['6 pommes Golden', '200g de sucre', '100g de beurre', '1 pâte feuilletée', 'Cannelle', 'Jus de citron'], steps: ['Préchauffez le four à 200°C.', 'Épluchez et coupez les pommes en quartiers.', 'Faites fondre le sucre dans une poêle jusqu\'à caramel.', 'Ajoutez le beurre et la cannelle.', 'Disposez les pommes dans le caramel.', 'Laissez cuire 15 minutes à couvert.', 'Recouvrez de pâte feuilletée en rentrant les bords.', 'Enfournez 25 minutes. Démoulez à l\'envers à la sortie.'], tags: ['dessert', 'classique', 'français', 'pommes', 'caramel'] },
  { id: 'r24', title: 'Profiteroles', description: 'Les choux fourrés de crème glacée et nappés de chocolat chaud.', difficulty: 'Difficile', prepTimeMin: 40, cookTimeMin: 25, servings: 6, ingredients: ['250ml d\'eau', '100g de beurre', '150g de farine', '4 œufs', '500ml de crème pâtissière', '200g de chocolat noir', '50ml de crème fraîche', '1 pincée de sel'], steps: ['Préchauffez le four à 200°C.', 'Portez l\'eau, le beurre et le sel à ébullition.', 'Hors du feu, ajoutez la farine d\'un coup.', 'Mélangez jusqu\'à détacher de la casserole.', 'Ajoutez les œufs un par un en mélangeant.', 'Formez des choux sur une plaque avec une poche à douille.', 'Enfournez 25 minutes sans ouvrir le four.', 'Garnissez de crème pâtissière et nappez de chocolat fondu.'], tags: ['dessert', 'classique', 'français', 'chocolat', 'choux'] },
  { id: 'r25', title: 'Clafoutis aux cerises', description: 'Le dessert limousin traditionnel aux cerises.', difficulty: 'Facile', prepTimeMin: 15, cookTimeMin: 35, servings: 6, ingredients: ['500g de cerises (dénoyautées)', '3 œufs', '100g de sucre', '80g de farine', '300ml de lait', '1 cuillère à café d\'extrait de vanille', 'Beurre', 'Sel'], steps: ['Préchauffez le four à 180°C.', 'Beurrez un plat à gratin.', 'Disposez les cerises dans le plat.', 'Battez les œufs avec le sucre.', 'Ajoutez la farine en pluie.', 'Mouillez avec le lait et la vanille.', 'Versez la pâte sur les cerises.', 'Enfournez 35 minutes jusqu\'à dorure.'], tags: ['dessert', 'classique', 'français', 'fruits', 'été'] },
  { id: 'r26', title: 'Madeleines', description: 'Les petits gâteaux moelleux en forme de coquillage.', difficulty: 'Facile', prepTimeMin: 15, cookTimeMin: 12, servings: 12, ingredients: ['100g de farine', '100g de sucre', '2 œufs', '100g de beurre fondu', '1 sachet de levure chimique', '1 cuillère à café d\'extrait de vanille', 'Miel pour la bosse'], steps: ['Faites fondre le beurre et laissez-le tiédir.', 'Battez les œufs et le sucre jusqu\'à blanchiment.', 'Ajoutez la vanille.', 'Incorporez la farine et la levure.', 'Ajoutez le beurre fondu.', 'Laissez reposer la pâte 1h au frais.', 'Beurrez et farinez les moules à madeleines.', 'Remplissez aux 3/4 et enfournez à 200°C pendant 12 minutes.'], tags: ['dessert', 'goûter', 'classique', 'français', 'moelleux'] },
  { id: 'r27', title: 'Île flottante', description: 'Les blancs d\'œufs flottants sur une crème anglaise.', difficulty: 'Moyen', prepTimeMin: 20, cookTimeMin: 15, servings: 4, ingredients: ['4 blancs d\'œufs', '500ml de lait', '4 jaunes d\'œufs', '80g de sucre', '1 gousse de vanille', 'Caramel liquide', 'Pralines concassées'], steps: ['Faites une crème anglaise : chauffez le lait avec la vanille.', 'Battez les jaunes avec le sucre.', 'Versez le lait chaud sur les jaunes en remuant.', 'Faites épaissir à feu doux sans bouillir.', 'Battez les blancs en neige ferme avec un peu de sucre.', 'Formez des îles à la cuillère et poêchez-les 2 min dans du lait frémissant.', 'Versez la crème anglaise dans des assiettes.', 'Déposez les îles et nappez de caramel.'], tags: ['dessert', 'classique', 'français', 'onctueux', 'crémeux'] },
  { id: 'r28', title: 'Fondant au chocolat', description: 'Le gâteau au cœur coulant de chocolat.', difficulty: 'Facile', prepTimeMin: 15, cookTimeMin: 12, servings: 4, ingredients: ['200g de chocolat noir', '150g de beurre', '3 œufs', '80g de sucre', '50g de farine', '1 pincée de sel'], steps: ['Préchauffez le four à 200°C.', 'Faites fondre le chocolat et le beurre ensemble.', 'Battez les œufs et le sucre.', 'Ajoutez le chocolat fondu aux œufs.', 'Incorporez la farine et le sel.', 'Beurrez et farinez 4 moules individuels.', 'Versez la pâte et enfournez 12 minutes.', 'Le centre doit rester coulant. Démoulez immédiatement.'], tags: ['dessert', 'chocolat', 'rapide', 'gourmand', 'fondant'] },
  { id: 'r29', title: 'Tiramisu', description: 'Le dessert italien au mascarpone et café.', difficulty: 'Facile', prepTimeMin: 20, cookTimeMin: 0, servings: 6, ingredients: ['250g de mascarpone', '3 œufs', '100g de sucre', '300g de biscuits à la cuillère', '300ml de café expresso refroidi', '2 cuillères à soupe de cacao amer', '2 cuillères à soupe d\'amaretto (optionnel)'], steps: ['Séparez les blancs des jaunes.', 'Battez les jaunes avec le sucre jusqu\'à blanchiment.', 'Ajoutez le mascarpone et mélangez.', 'Battez les blancs en neige et incorporez-les.', 'Mélangez le café avec l\'amaretto.', 'Trempez les biscuits dans le café rapidement.', 'Alternez couches de biscuits et crème.', 'Réfrigérez au moins 4h. Saupoudrez de cacao avant de servir.'], tags: ['dessert', 'italien', 'café', 'sans cuisson', 'classique'] },
  { id: 'r30', title: 'Crêpes suzette', description: 'Les crêpes au beurre d\'orange flambées.', difficulty: 'Moyen', prepTimeMin: 30, cookTimeMin: 15, servings: 4, ingredients: ['250g de farine', '3 œufs', '500ml de lait', '50g de beurre fondu', '1 pincée de sel', '2 oranges', '100g de sucre', '100ml de Grand Marnier', '100g de beurre'], steps: ['Préparez la pâte : farine, œufs, lait, beurre, sel.', 'Laissez reposer 1h.', 'Faites cuire les crêpes une par une.', 'Pressez les oranges et récupérez le zeste.', 'Faites un caramel avec le sucre.', 'Ajoutez le jus d\'orange et le beurre.', 'Pliez les crêpes et nappez de sauce.', 'Flambez au Grand Marnier à table.'], tags: ['dessert', 'classique', 'français', 'festif', 'flambé'] },

  // --- PLATS RAPIDES ---
  { id: 'r31', title: 'Omelette aux fines herbes', description: 'L\'omelette baveuse parfumée au persil et ciboulette.', difficulty: 'Facile', prepTimeMin: 5, cookTimeMin: 5, servings: 2, ingredients: ['4 œufs', 'Persil frais', 'Ciboulette', '20g de beurre', 'Sel et poivre'], steps: ['Battez les œufs avec sel et poivre.', 'Ciselez les herbes finement.', 'Ajoutez les herbes aux œufs battus.', 'Faites fondre le beurre dans une poêle à feu moyen.', 'Versez les œufs et laissez prendre sans remuer.', 'Quand le dessous est doré, pliez l\'omelette.', 'Laissez cuire 1 minute encore.', 'Servez immédiatement, baveuse à l\'intérieur.'], tags: ['plat', 'rapide', 'œufs', 'herbes', 'facile'] },
  { id: 'r32', title: 'Pasta al pesto', description: 'Les pâtes au pesto genovès basilic et pignons.', difficulty: 'Facile', prepTimeMin: 10, cookTimeMin: 10, servings: 4, ingredients: ['400g de penne', '1 bouquet de basilic frais', '50g de pignons de pin', '2 gousses d\'ail', '80g de parmesan', '100ml d\'huile d\'olive', 'Sel et poivre'], steps: ['Mixez le basilic, l\'ail et les pignons au blender.', 'Ajoutez l\'huile d\'olive en filet.', 'Incorporez le parmesan râpé.', 'Faites cuire les pâtes al dente.', 'Réservez une louche d\'eau de cuisson.', 'Mélangez les pâtes chaudes avec le pesto.', 'Ajoutez un peu d\'eau de cuisson pour détendre.', 'Servez avec un filet d\'huile et du parmesan.'], tags: ['plat', 'pâtes', 'italien', 'rapide', 'herbes'] },
  { id: 'r33', title: 'Tacos maison', description: 'Les tacos mexicains au bœuf épicé et guacamole.', difficulty: 'Facile', prepTimeMin: 20, cookTimeMin: 15, servings: 4, ingredients: ['500g de bœuf haché', '8 tortillas de maïs', '2 avocats', '2 tomates', '1 oignon rouge', '1 citron vert', 'Coriandre', 'Cumin, paprika, chili'], steps: ['Assaisonnez le bœuf avec cumin, paprika et chili.', 'Faites dorer le bœuf haché à la poêle.', 'Préparez le guacamole : écrasez les avocats avec le citron.', 'Ajoutez l\'oignon émincé et la coriandre au guacamole.', 'Coupez les tomates en dés pour la salsa.', 'Réchauffez les tortillas.', 'Garnissez avec le bœuf, guacamole et salsa.', 'Servez avec des quartiers de citron vert.'], tags: ['plat', 'mexicain', 'rapide', 'festif', 'épicé'] },
  { id: 'r34', title: 'Salade César', description: 'La salade romaine au poulet croustillant et sauce César.', difficulty: 'Facile', prepTimeMin: 15, cookTimeMin: 15, servings: 2, ingredients: ['1 laitue romaine', '2 escalopes de poulet', '50g de parmesan', '20g de chapelure', '1 jaune d\'œuf', '1 gousse d\'ail', '2 anchois', 'Jus de citron', 'Huile d\'olive'], steps: ['Préparez la sauce : mixez l\'ail, les anchois, le jaune d\'œuf.', 'Ajoutez l\'huile en filet et le jus de citron.', 'Panez le poulet avec la chapelure.', 'Faites dorer le poulet à la poêle.', 'Coupez la laitue en morceaux.', 'Coupez le poulet en tranches.', 'Mélangez la salade avec la sauce.', 'Disposez le poulet dessus et parsemez de parmesan.'], tags: ['salade', 'classique', 'poulet', 'rapide'] },
  { id: 'r35', title: 'Shakshuka', description: 'Les œufs pochés dans une sauce tomate épicée.', difficulty: 'Facile', prepTimeMin: 10, cookTimeMin: 20, servings: 4, ingredients: ['4 œufs', '400g de tomates concassées', '1 poivron', '1 oignon', '2 gousses d\'ail', 'Cumin, paprika', 'Coriandre', 'Huile d\'olive', 'Pain de campagne'], steps: ['Émincez l\'oignon et coupez le poivron en dés.', 'Faites revenir dans l\'huile d\'olive.', 'Ajoutez l\'ail, le cumin et le paprika.', 'Versez les tomates concassées.', 'Laissez mijoter 15 minutes.', 'Creusez 4 puits et cassez les œufs dedans.', 'Couvrez et laissez pocher 5-7 minutes.', 'Parsemez de coriandre et servez avec du pain.'], tags: ['plat', 'moyen-orient', 'œufs', 'rapide', 'végétarien'] },

  // --- AUTRES RECETTES VARIÉES ---
  { id: 'r36', title: 'Bœuf Stroganoff', description: 'Le ragoût russe au bœuf, champignons et crème.', difficulty: 'Moyen', prepTimeMin: 15, cookTimeMin: 25, servings: 4, ingredients: ['500g de bœuf en lanières', '250g de champignons', '1 oignon', '200ml de crème fraîche', '1 cuillère à soupe de moutarde', '2 cuillères à soupe de paprika', '300g de riz', 'Persil'], steps: ['Faites dorer le bœuf en lanières à feu vif.', 'Retirez et faites revenir l\'oignon émincé.', 'Ajoutez les champignons et la paprika.', 'Remettez le bœuf, ajoutez la moutarde et la crème.', 'Laissez mijoter 15 minutes.', 'Faites cuire le riz à part.', 'Assaisonnez de sel et poivre.', 'Servez le stroganoff sur le riz avec du persil.'], tags: ['plat', 'russe', 'crémeux', 'champignons'] },
  { id: 'r37', title: 'Quenelles de brochet', description: 'Les quenelles moelleuses en sauce Nantua.', difficulty: 'Difficile', prepTimeMin: 40, cookTimeMin: 25, servings: 4, ingredients: ['200g de chair de brochet', '200g de farine', '3 œufs', '100ml de crème', '50g de beurre', 'Sauce Nantua (écrevisses)', 'Muscade', 'Sel et poivre'], steps: ['Mixez la chair de poisson avec les œufs et la crème.', 'Ajoutez la farine progressivement.', 'Assaisonnez de muscade, sel et poivre.', 'Formez les quenelles avec deux cuillères.', 'Poêchez-les 15 minutes dans un bouillon frémissant.', 'Préparez la sauce Nantua.', 'Égouttez les quenelles et nappez de sauce.', 'Servez avec du riz ou des pommes duchesse.'], tags: ['plat', 'classique', 'français', 'poisson', 'festif'] },
  { id: 'r38', title: 'Taboulé libanais', description: 'La salade de persil et boulghour au citron.', difficulty: 'Facile', prepTimeMin: 20, cookTimeMin: 0, servings: 4, ingredients: ['200g de boulghour', '3 bottes de persil plat', '1 botte de menthe', '3 tomates', '1 oignon nouveau', '2 citrons', '4 cuillères à soupe d\'huile d\'olive', 'Sel et poivre'], steps: ['Faites gonfler le boulghour dans de l\'eau chaude 10 minutes.', 'Égouttez bien.', 'Ciselez très finement le persil et la menthe.', 'Coupez les tomates et l\'oignon en petits dés.', 'Mélangez tous les ingrédients.', 'Assaisonnez avec le jus de citron, l\'huile, sel et poivre.', 'Réfrigérez 30 minutes avant de servir.', 'Servez frais avec des feuilles de vigne.'], tags: ['salade', 'libanais', 'frais', 'santé', 'végétarien'] },
  { id: 'r39', title: 'Gaspacho andalou', description: 'La soupe froide de tomates d\'Espagne.', difficulty: 'Facile', prepTimeMin: 15, cookTimeMin: 0, servings: 4, ingredients: ['1kg de tomates mûres', '1 concombre', '1 poivron rouge', '1 gousse d\'ail', '100ml d\'huile d\'olive', '2 cuillères à soupe de vinaigre de Xérès', 'Sel et poivre', 'Garniture : dés de concombre, poivron, oignon'], steps: ['Mondez les tomates et coupez-les en morceaux.', 'Coupez le concombre et le poivron en morceaux.', 'Mixez tous les légumes avec l\'ail.', 'Ajoutez l\'huile d\'olive et le vinaigre.', 'Assaisonnez et mixez finement.', 'Réfrigérez au moins 2 heures.', 'Servez bien froid.', 'Garnissez de petits dés de légumes et d\'un filet d\'huile.'], tags: ['soupe', 'froid', 'espagnol', 'été', 'frais', 'santé'] },
  { id: 'r40', title: 'Lasagnes bolognaise', description: 'Les lasagnes traditionnelles à la sauce tomate viandée.', difficulty: 'Moyen', prepTimeMin: 30, cookTimeMin: 45, servings: 8, ingredients: ['12 feuilles de lasagnes', '500g de bœuf haché', '1 boîte de tomates concassées', '1 oignon', '2 carottes', '1 céleri', 'Béchamel (500ml lait, 50g beurre, 50g farine)', 'Muscade', 'Gruyère râpé'], steps: ['Faites revenir l\'oignon, carottes et céleri émincés.', 'Ajoutez le bœuf haché et faites dorer.', 'Versez les tomates et laissez mijoter 30 minutes.', 'Préparez la béchamel.', 'Dans un plat, alternez : sauce, lasagnes, béchamel.', 'Terminez par la béchamel et le gruyère.', 'Enfournez à 180°C pendant 45 minutes.', 'Laissez reposer 10 minutes avant de couper.'], tags: ['plat', 'italien', 'gratin', 'familial', 'classique'] },
  { id: 'r41', title: 'Risotto aux champignons', description: 'Le risotto crémeux aux cèpes et paris.', difficulty: 'Moyen', prepTimeMin: 10, cookTimeMin: 25, servings: 4, ingredients: ['300g de riz arborio', '200g de champignons de Paris', '50g de cèpes séchés', '1 oignon', '1 verre de vin blanc', '750ml de bouillon', '50g de parmesan', '50g de beurre', 'Persil'], steps: ['Faites tremper les cèpes séchés dans l\'eau chaude.', 'Émincez l\'oignon et les champignons.', 'Faites revenir l\'oignon dans le beurre.', 'Ajoutez le riz et nacrez-le 2 minutes.', 'Déglacez au vin blanc.', 'Ajoutez le bouillon louche par louche en remuant.', 'Ajoutez les champignons mi-cuisson.', 'Terminez par le parmesan et le beurre.'], tags: ['plat', 'italien', 'champignons', 'crémeux', 'risotto'] },
  { id: 'r42', title: 'Pavé de thon mi-cuit', description: 'Le thon saisissi et mariné au sésame.', difficulty: 'Moyen', prepTimeMin: 15, cookTimeMin: 5, servings: 2, ingredients: ['2 pavés de thon rouge', '3 cuillères à soupe de sauce soja', '1 cuillère à soupe de miel', 'Graines de sésame', 'Gingembre frais', '1 cuillère à soupe d\'huile de sésame'], steps: ['Mélangez la sauce soja, le miel et le gingembre râpé.', 'Marinez le thon 30 minutes au réfrigérateur.', 'Égouttez les pavés et roulez-les dans les graines de sésame.', 'Faites chauffer l\'huile de sésame dans une poêle très chaude.', 'Saisissez les pavés 1 minute par face.', 'Le centre doit rester rosé.', 'Coupez en tranches épaisses.', 'Servez avec une salade d\'algues ou de concombre.'], tags: ['plat', 'poisson', 'japonais', 'sain', 'rapide'] },
  { id: 'r43', title: 'Fondue savoyarde', description: 'Le fromage fondu savoyard à partager.', difficulty: 'Facile', prepTimeMin: 10, cookTimeMin: 10, servings: 4, ingredients: ['400g de comté râpé', '200g de gruyère râpé', '200g d\'emmental râpé', '300ml de vin blanc sec', '1 gousse d\'ail', '1 cuillère à soupe de maïzena', 'Kirsch', 'Pain de campagne', 'Sel et poivre'], steps: ['Frottez le caquelon avec la gousse d\'ail.', 'Versez le vin blanc et portez à ébullition.', 'Ajoutez le fromage en pluie en remuant en huit.', 'Diluez la maïzena dans un peu de vin froid.', 'Ajoutez pour épaissir la fondue.', 'Ajoutez le Kirsch.', 'Servez avec le pain coupé en cubes.', 'Remuez régulièrement pour éviter que le fromage n\'attache.'], tags: ['plat', 'montagne', 'fromage', 'hiver', 'convivial'] },
  { id: 'r44', title: 'Galettes bretonnes', description: 'Les crêpes de sarrasin de Bretagne à la complète.', difficulty: 'Moyen', prepTimeMin: 20, cookTimeMin: 15, servings: 4, ingredients: ['250g de farine de sarrasin', '1 œuf', '500ml d\'eau', '1 pincée de sel', '4 tranches de jambon', '100g de gruyère', '4 œufs', 'Beurre demi-sel'], steps: ['Mélangez la farine, l\'œuf, l\'eau et le sel.', 'Laissez reposer 1h.', 'Beurrez une poêle et versez une louche de pâte.', 'Faites cuire 2 minutes de chaque côté.', 'Cassez un œuf au centre de la galette.', 'Ajoutez le jambon et le gruyère.', 'Repliez les bords en carré.', 'Laissez gratiner 2 minutes et servez.'], tags: ['plat', 'breton', 'sarrasin', 'classique', 'galette'] },
  { id: 'r45', title: 'Laksa malaisienne', description: 'La soupe de nouilles épicée au lait de coco.', difficulty: 'Moyen', prepTimeMin: 15, cookTimeMin: 20, servings: 4, ingredients: ['200g de nouilles de riz', '400ml de lait de coco', '400ml de bouillon de poulet', '2 cuillères à soupe de pâte de curry laksa', '200g de crevettes', '200g de tofu ferme', 'Pousses de soja', 'Cilantro', 'Citron vert', 'Pâte de crevettes'], steps: ['Faites revenir la pâte de curry dans un peu d\'huile.', 'Versez le bouillon et le lait de coco.', 'Portez à ébullition et laissez mijoter 10 minutes.', 'Ajoutez les crevettes et le tofu en cubes.', 'Faites cuire les nouilles de riz à part.', 'Répartissez les nouilles dans les bols.', 'Versez la soupe chaude dessus.', 'Garnissez de pousses de soja, cilantro et citron vert.'], tags: ['plat', 'asiatique', 'épicé', 'nouilles', 'exotique'] },
  { id: 'r46', title: 'Pintade aux figues', description: 'La pintade rôtie aux figues fraîches et au miel.', difficulty: 'Moyen', prepTimeMin: 15, cookTimeMin: 60, servings: 4, ingredients: ['1 pintade entière', '8 figues fraîches', '3 cuillères à soupe de miel', 'Thym frais', '200ml de bouillon', '1 oignon', '30g de beurre', 'Sel et poivre'], steps: ['Préchauffez le four à 200°C.', 'Farcissez la pintade de thym et d\'un demi-oignon.', 'Faites dorer la pintade au beurre dans une cocotte.', 'Arrosez de miel et enfournez 45 minutes.', 'Ajoutez les figues 15 minutes avant la fin.', 'Arrosez régulièrement du jus de cuisson.', 'Laissez reposer 10 minutes.', 'Servez avec le jus de cuisson réduit.'], tags: ['plat', 'volaille', 'figues', 'miel', 'automne', 'festif'] },
  { id: 'r47', title: 'Buddha bowl', description: 'Le bol sain et coloré aux céréales et légumes.', difficulty: 'Facile', prepTimeMin: 15, cookTimeMin: 20, servings: 2, ingredients: ['200g de quinoa', '1 avocat', '1 patate douce', '200g de pois chiches', '1 betterave', 'Sauce tahini (citron, ail, tahini)', 'Graines de sésame', 'Roquette'], steps: ['Faites cuire le quinoa selon les instructions.', 'Rôtissez la patate douce et la betterave au four à 200°C pendant 25 minutes.', 'Faites griller les pois chiches avec du cumin.', 'Préparez la sauce tahini.', 'Coupez l\'avocat en tranches.', 'Disposez tous les ingrédients dans des bols.', 'Nappez de sauce tahini.', 'Parsemez de graines de sésame et de roquette.'], tags: ['plat', 'santé', 'végétarien', 'bowl', 'coloré'] },
  { id: 'r48', title: 'Baba au rhum', description: 'Le gâteau imbibé de sirop au rhum des Antilles.', difficulty: 'Moyen', prepTimeMin: 25, cookTimeMin: 35, servings: 8, ingredients: ['200g de farine', '100g de sucre', '3 œufs', '15g de levure boulangère', '100ml de lait', '80g de beurre', 'Pour le sirop : 200g sucre, 200ml eau, 100ml rhum', 'Crème pâtissière'], steps: ['Délayez la levure dans le lait tiède.', 'Mélangez farine, sucre et œufs.', 'Ajoutez le lait avec la levure et le beurre fondu.', 'Laissez lever 1h dans un moule beurré.', 'Enfournez à 180°C pendant 35 minutes.', 'Préparez le sirop : eau + sucre, puis ajoutez le rhum.', 'Imbibez le baba de sirop chaud.', 'Servez avec de la crème pâtissière.'], tags: ['dessert', 'rhum', 'antillais', 'classique', 'festif'] },
  { id: 'r49', title: 'Gratin de macaronis', description: 'Les macaronis au fromage gratinés au four.', difficulty: 'Facile', prepTimeMin: 10, cookTimeMin: 20, servings: 4, ingredients: ['400g de macaronis', '200ml de crème fraîche', '200ml de lait', '200g de cheddar râpé', '50g de beurre', '50g de farine', 'Muscade', 'Sel et poivre'], steps: ['Préchauffez le four à 200°C.', 'Faites cuire les macaronis al dente.', 'Préparez une béchamel avec le beurre, farine et lait.', 'Ajoutez la crème et la moitié du fromage.', 'Mélangez les macaronis avec la sauce.', 'Versez dans un plat à gratin.', 'Parsemez du reste de fromage.', 'Enfournez 20 minutes jusqu\'à bulles et dorure.'], tags: ['plat', 'gratin', 'fromage', 'confort', 'familial'] },
  { id: 'r50', title: 'Sorbet mangue-passion', description: 'Le sorbet tropical rafraîchissant aux fruits.', difficulty: 'Facile', prepTimeMin: 10, cookTimeMin: 0, servings: 4, ingredients: ['2 mangues mûres', '4 fruits de la passion', '100g de sucre', '200ml d\'eau', '1 cuillère à soupe de jus de citron'], steps: ['Faites un sirop avec l\'eau et le sucre.', 'Laissez refroidir.', 'Mixez les mangues en purée lisse.', 'Extrayez la pulpe des fruits de la passion.', 'Mélangez la purée de mangue, la pulpe de passion et le sirop.', 'Ajoutez le jus de citron.', 'Versez dans une sorbetière et turbiner 25 minutes.', 'Gardez au congélateur jusqu\'au service.'], tags: ['dessert', 'glacé', 'tropical', 'frais', 'été'] },
];

/* ═══ FUN FACTS ═══ */
export const FUN_FACTS: string[] = [
  'Les abeilles dansent pour communiquer la localisation des fleurs à leurs congénères.',
  'Le cœur d\'une baleine bleue bat si lentement qu\'il ne bat que deux fois par minute.',
  'Les dauphins dorment d\'un seul œil pour garder une moitié du cerveau éveillée.',
  'Le premier site web au monde a été créé en 1991 par Tim Berners-Lee.',
  'Un nuage moyen pèse environ 500 tonnes, soit l\'équivalent de 100 éléphants.',
  'Le chat est l\'animal le plus populaire sur Internet, devant le chien.',
  'En Finlande, il existe un championnat annuel de lancer de téléphones portables.',
  'Les pieuvres ont trois cœurs et du sang bleu.',
  'Le son d\'un craquement de doigts se produit en 7 millisecondes.',
  'La tour Eiffel peut grandir de 15 cm en été à cause de la dilatation thermique.',
  'Les bananes sont techniquement des baies, pas les fraises.',
  'Le premier SMS de l\'histoire a été envoyé en 1992 avec le message "Joyeux Noël".',
];

/* ═══ JOKES ═══ */
export const JOKES: { setup: string; punchline: string }[] = [
  { setup: 'Que fait une fraise sur un cheval ?', punchline: 'Tagada tagada !' },
  { setup: 'Pourquoi les plongeurs plongent-ils toujours en arrière ?', punchline: 'Parce que sinon ils tomberaient dans le bateau.' },
  { setup: 'Quel est le comble pour un électricien ?', punchline: 'De ne pas être au courant.' },
  { setup: 'Que dit un informaticien quand il a froid ?', punchline: 'Fermez la fenêtre !' },
  { setup: 'Pourquoi les maths sont-elles tristes ?', punchline: 'Parce qu\'elles ont trop de problèmes.' },
  { setup: 'Qu\'est-ce qu\'un crocodile qui surveille la cour de récréation ?', punchline: 'Un surveillant.' },
  { setup: 'Pourquoi le chat est-il allé à l\'ordinateur ?', punchline: 'Pour surveiller la souris.' },
  { setup: 'Que fait un SMS dans un désert ?', punchline: 'Un texto.' },
  { setup: 'Comment appelle-t-on un chat tombé dans un pot de peinture le jour de Noël ?', punchline: 'Un chat peint de Noël.' },
  { setup: 'Pourquoi les oiseaux ne se servent-ils pas de Facebook ?', punchline: 'Parce qu\'ils ont déjà Twitter.' },
];

/* ═══ QUOTES ═══ */
export const QUOTES: { text: string; author: string }[] = [
  { text: 'La vie est un mystère qu\'il faut vivre, et non un problème à résoudre.', author: 'Gandhi' },
  { text: 'Le bonheur est parfois caché dans une inconnue.', author: 'Baudelaire' },
  { text: 'La simplicité est la sophistication suprême.', author: 'Léonard de Vinci' },
  { text: 'Chaque matin nous naissons à nouveau.', author: 'Bouddha' },
  { text: 'Le succès, c\'est d\'aller d\'échec en échec sans perdre son enthousiasme.', author: 'Churchill' },
  { text: 'La créativité, c\'est l\'intelligence qui s\'amuse.', author: 'Einstein' },
  { text: 'Celui qui déplace une montagne commence par déplacer de petites pierres.', author: 'Confucius' },
  { text: 'La seule façon de faire du bon travail est d\'aimer ce que vous faites.', author: 'Steve Jobs' },
  { text: 'Le voyage de mille lieues commence toujours par un premier pas.', author: 'Lao Tseu' },
  { text: 'Soyez le changement que vous voulez voir dans le monde.', author: 'Gandhi' },
];

/* ═══ GREETINGS ═══ */
export const MORNING_GREETINGS = {
  sunny: [
    'Bonjour ! Il fait un temps magnifique aujourd\'hui. Que puis-je faire pour vous ?',
    'Bonjour ! Le soleil brille, c\'est une belle journée pour se lancer. Comment puis-je vous aider ?',
    'Bonjour ! Quelle belle matinée ! Je suis prêt à vous accompagner dans votre journée.',
  ],
  rainy: [
    'Bonjour ! Il pleut un peu aujourd\'hui, c\'est parfait pour rester au chaud. Que puis-je faire pour vous ?',
    'Bonjour ! Un temps de pluie, l\'occasion de prendre son temps. Comment puis-je vous aider ?',
  ],
  cold: [
    'Bonjour ! Il fait frais ce matin, n\'hésitez pas à vous couvrir. Que puis-je faire pour vous ?',
    'Bonjour ! Une journée fraîche s\'annonce. Au chaud, comment puis-je vous aider ?',
  ],
  default: [
    'Bonjour ! Comment puis-je vous aider ce matin ?',
    'Bonjour ! Je suis là pour vous accompagner dans votre journée.',
    'Bonjour ! Belle journée à vous. Que puis-je faire pour vous ?',
  ],
};

export const EVENING_GREETINGS = {
  default: [
    'Bonsoir ! J\'espère que vous avez passé une bonne journée. Que puis-je faire pour vous ?',
    'Bonsoir ! La soirée s\'installe. Comment puis-je vous aider ?',
    'Bonsoir ! Je suis là pour vous ce soir. N\'hésitez pas à me demander ce que vous souhaitez.',
  ],
};
